- Library/Formula/erlang.rb
This solves the problem in #372 of erlang not installing
> Correctly disable javac flag when compiling erlang on < 10.6

- Library/Formula/mercurial.rb
from https://mercurial.selenic.com/
to https://www.mercurial-scm.org/
fixes #455
> mercurial: update URL

- Library/Formula/icu4c.rb
The assembler available on Tiger does not understand the `.balign`
directive, but `.p2align` can be used in its place.
Fixes #325.
> icu4c: Fix build on Tiger

- Library/Formula/zsh.rb
I updated zsh's version from 5.1.1 to 5.2 mostly because the 5.1.1 version isn't available in those locations anymore (moved to the old versions folder) and because 5.2 is newer. I have tested this (including building + actually using zsh built).
> zsh: update version

- Library/Formula/cairo.rb
Tiger ships with an old X11 that does not include the XCB (X protocol
C-language Binding), but the Xlib backend builds just fine.
The build failure at https://gist.github.com/anonymous/5695285 is
caused by a defect in the cairo build system that has been fixed
upstream.
Fixes #69.
> cairo: Fix building Cairo w/ X11 on Tiger

- Library/Formula/gcc.rb
- Library/Homebrew/extend/ENV/std.rb
This is still a WIP; GCC still fails to build with these patches at this time.
> Fix building GCC on 10.4 Intel

- Library/Formula/ruby.rb
Even though I did not test it, I think that the first two patches are needed on Leopard as well, because:
- `fgetattrlist` was introduced in 10.6
- `mach_task_basic_info_data_t` is not available even on 10.6
I am not sure about `win32.S` (maybe not needed on Leopard? likely not needed on ppc).
> ruby: Fix build of 2.4.1 on Tiger i386

- Library/Formula/ruby.rb
Build currently failing due to use of `fgetattrlist`, first introduced in 10.6.
> ruby 2.4.1

- Library/Homebrew/cmd/search.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/test/test_formulary.rb
Adapted from https://github.com/Homebrew/brew/pull/812.
I'm going to be getting Tigerbrew onto upstream Homebrew/brew at some point in the future, but this is a prerequisite for building the Ruby binary packages that are necessary to do so.
> Import homebrew's formula@version

- Library/Homebrew/extend/fileutils.rb
This is what Homebrew/brew uses; I'll migrate things from `make_path` in a future PR.
> Add a helper to determine make path on Tiger

- Library/Formula/lsof.rb
Tiger ships a userland libproc, but doesn't ship a header for it. Thanks to @ranma42 for the help getting the headers set up properly!
I need to check that this is the case on 10.4.11-ppc, but I think it probably will be. That won't hold up merging.
Fixes #426.
> lsof: import from homebrew/dupes, and fix build on Tiger

- Library/Formula/harfbuzz.rb
This is sufficient to fix the build for harfbuzz in my VM.
Please confirm whether it works in other environments, as issue #70 mentions that the build is not fixed by `ld64`.
> Fix harfbuzz

- Library/Formula/qemu.rb
> qemu: fails with gcc-4.0, gcc-4.2

- Library/Formula/libutil.rb
This is shipped by newer versions of OS X, and used by some packages.
> libutil 11

- Library/Formula/qemu.rb
Fixes #494.
This currently doesn't completely build due to a strange error, looks like the pixman CFLAGS are being passed incorrectly: https://gist.github.com/d590fb19ba97fea798970cec796bbdf9 Truncation, maybe?
```
I/usr/local/Cellar/pixman/0.32.6/include/pixman-1 -I/private/tmp/qemu20170424-27348-k1x6mt/qemu-2.4.0.1/dtc/libfdt -m32 -DOS_OBJECT_USE_OBJC=0 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common  -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits -fstack-protector-strong -I/usr/local/Cellar/gnutls/3.3.18/include …
```
> (WIP) Fix qemu on 10.4

- Library/Formula/gcc44.rb
- Library/Formula/gcc45.rb
- Library/Formula/gcc46.rb
- Library/Formula/gcc47.rb
- Library/Formula/gcc48.rb
- Library/Formula/gcc49.rb
- Library/Formula/gcc5.rb
- Library/Formula/gcc6.rb
Eventually these will be replaced with versions using Homebrew's new naming format, but these will allow users who already had them to use them.
cc @dcwar 
Fixes #499.
> Import gcc formulae from homebrew/versions

- Library/Homebrew/tap_constants.rb
Cherry-picked from https://github.com/homebrew/brew/commit/0c44ce2a38d. This fixes `brew search` and certain other commands that went through `Formulary.from_rack`.
> tap_constants: allow formulae to have @ in name.

- Library/Formula/qemu.rb
Looks like a victim of the changing git ref length.
Fixes #521.
> qemu: fix patch sha256

- Library/Formula/curl.rb
This allows a curl that cannot handle modern SSL certificates to install a newer version.
Fixes #506
Refs #530
Signed-off-by: Misty De Meo <mistydemeo@gmail.com>
> curl: add HTTP mirror.

- Library/Formula/apple-gcc42.rb
This is a bit too important to let it go missing. Relying on AT&T to host it forever feels dangerous.
> apple-gcc42: mirror on archive.org

- Library/Formula/gcc.rb
- Library/Formula/gcc6.rb
> gcc{6,7}: build without plugins on Leopard, too

- Library/Formula/python3.rb
Postinstall was failing with these errors, which caused (perhaps among other problems?) easy_install and pip3 to not be linked & added to PATH properly.
Fixes #441.
`vivtop-g4:~/Desktop vivlim$ brew postinstall python3
Error: wrong number of arguments (2 for 1)
Please report this bug:
https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Formula/python3.rb:220:in '[]'
/usr/local/Library/Formula/python3.rb:220:in 'post_install'
/usr/local/Library/Homebrew/formula.rb:765:in 'run_post_install'
/usr/local/Library/Homebrew/cmd/postinstall.rb:3:in 'postinstall'
/usr/local/Library/Homebrew/cmd/postinstall.rb:3:in 'each'
/usr/local/Library/Homebrew/cmd/postinstall.rb:3:in 'postinstall'
/usr/local/Library/brew.rb:143:in 'send'
/usr/local/Library/brew.rb:143 …
> Fix python3 postinstall

- Library/Formula/curl.rb
Because the AskApache server now redirects HTTP to HTTPS.
> curl: change HTTP mirror

- Library/Formula/gmp.rb
Fixes error ``Invalid configuration `powerpccore2-apple-darwin8': machine `powerpccore2-apple' not recognized`` during configure step when building bottle on Intel.
> gmp: fix bottling on Intel

- Library/Formula/xz.rb
Looks like fossies.org removes older versions.
> xz: fix 410 on primary mirror

- Library/Formula/ppl011.rb
Fix building on Tiger by changing dependency to Tigerbrew's m4, and fix installing for all due to "No available formula for ppl10" error.
> ppl011: fix dependent & conflicting formulae

- Library/Formula/gcc45.rb
Otherwise fails with `Building GCC with plugin support requires a host that supports -fPIC, -shared, -ldl and -rdynamic`. Builds otherwise work on G3/G4/Intel Tiger & Intel Leopard.
> gcc45: fix build on 10.5 PPC by disabling plugins

- Library/Formula/gcc47.rb
Pulled fixes from gcc46 and gcc48 formulae. (Still looking into why I get `unrecognized command line option '-qversion'` when building on 10.5.)
> gcc47: fix build on 10.4

- Library/Homebrew/cmd/vendor-install.sh
- Library/Homebrew/vendor/Digest/README
- Library/Homebrew/vendor/Digest/SHA/PurePerl.pm
- Library/Homebrew/vendor/sha256
- Library/Homebrew/vendor/shasum
This fixes #561, which I tracked down with @luigi30's help to a broken SHA256 implementation in Ruby 1.8.2 on G3 and G4 (but not G4e) systems.
> vendor-install: use pure Perl to avoid broken sha2

- Library/Homebrew/cmd/vendor-install.sh
Fixes #593.
I was checking the CPU model incorrectly for PPC, which broke my attempt at guarding G3 and G4 from using Ruby 1.8.2's sha2. This fixes that check, and also fixes another bug that was hidden by this other bug. It's bugs all the way down!
cc @valtteri
> Fix vendored Ruby script on G3 (again)

- Library/Homebrew/cmd/vendor-install.sh
This is added to skip Ruby 1.8.2 on OSX 10.4 running on PPC7450 (Mac mini G4)
on Mac mini G4, the cpu_type is 18 but cpu_family is 11, and will cause failure as Ruby buggy sha256 logic will be used.
> Fix ruby 1.8.2 detection to skip ppc7450 cpu

- Library/Formula/ninja.rb
`gtest` is no longer available at the old URL.
There are a couple of alternatives including Googles own GitHub page however the hash isn't matching.
```
https://github.com/google/googletest/archive/release-1.7.0.zip
https://web.archive.org/web/20160617081653if_/http://googletest.googlecode.com/files/gtest-1.7.0.zip
https://src.fedoraproject.org/lookaside/pkgs/gtest/gtest-1.7.0.zip/2d6ec8ccdf5c46b05ba54a9fd1d130d7/gtest-1.7.0.zip
```
> ninja: Fix dependency URL

- Library/Formula/fortune.rb
The source download requires having an FTP URL instead of an HTTP URL to fetch the file.
> Update url in fortune.rb

- Library/Formula/libsoxr.rb
> libsoxr: needs ld64

- Library/Formula/openssl.rb
the urls in the openssl formula are outdated and return 404
> openssl: fix urls

- Library/Formula/sdl2_gfx.rb
Thanks so much for making tigerbrew!
I ran into a build error with an eMac running Tiger:
```
$ brew install sdl2_gfx
...
config.status: executing libtool commands
config.status: executing depfiles commands
Options summary:
* --enable-mmx: yes
==> make install
/bin/sh ./libtool --tag=CC   --mode=compile /usr/bin/gcc-4.0 -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"SDL2_gfx\" -DVERSION=\"1.0.0\" -DSIZEOF_LONG=4 -I.   -F/usr/local/Frameworks  -Os -w -pipe -mcpu=7450 …
```
> sdl2_gfx: Disable MMX on PPC

- Library/Formula/ecl.rb
Thanks again for making tigerbrew!
This PR fixes a broken source URL for ecl 16.
```
$ brew install --build-bottle ecl
==> Downloading https://common-lisp.net/project/ecl/files/ecl-16.0.0.tgz
/usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl -fLA Homebrew/0.9.5 (Macintosh; powerpc Mac OS X 10.4.11) curl/7.58.0 https://common-lisp.net/project/ecl/files/ecl-16.0.0.tgz -C 0 -o /Users/cell/Library/Caches/Homebrew/ecl-16.0.0.tgz.incomplete
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ecl"
Download failed: …
```
> ecl: fix source URL

- Library/Formula/graphviz.rb
This PR fixes a broken URL for graphviz sources.
The official graphviz sources have been moved to a new location, and no longer go back as far as 2.38.
This PR switches to using the Open Source Lab mirror, which goes back to 2.38 and also supports plain HTTP.
> graphviz: replace 404'ed source URL

- Library/Homebrew/cmd/search.rb
- Library/Homebrew/official_taps.rb
This limits official taps to the ones that still exist and removes cask from the default search.
Fixes #705.
> Trim searchable taps

- .gitignore
I somehow missed this even though they were added *years* ago. 🙈 
Fixes #716.
> Add portable Ruby/curl to gitignore

- Library/Homebrew/cmd/vendor-install.sh
cc @ticky, who pointed this out awhile ago - users might think something is wrong if it takes this long for Tigerbrew to respond when installing these for the first time.
> vendor-install: add message that Tigerbrew is installing tools

- CONTRIBUTING.md
These links went to the upstream Homebrew project, and some of them are no longer at that URL. This updates them to point at this project’s copy.
> Point links in contribution guide at Tigerbrew

- README.md
This adds the required Xcode versions for Tiger and Leopard to the Readme.
These links are more current than the https://developer.apple.com/xcode/downloads/ url currently emitted `brew doctor` (which redirects to Apple’s beta software downloads), and each list a single Xcode version in their results pane. At least until Apple change the format again! 😅
> Add Xcode links and information to Readme

- Library/Homebrew/cmd/vendor-curl.sh
- Library/Homebrew/utils/ruby.sh
The vendor installation and subsequent checksum verification of curl and ruby takes quite a long time on older machines; somewhere in the order of an hour on my PowerBook G4 Titanium’s 867 MHz CPU and ailing disk drive.
For that entire time, unless you’ve set Tigerbrew to verbose, you’re given _absolutely no_ output until the “real” Ruby infrastructure takes over, which is easy to mistake for nothing actually happening!
For that reason, and having talked to @mistydemeo about it in person, I’d propose removing the `--quiet` flags from these steps, so that `vendor-install` _at least_ goes and prints that it’s downloading stuff.
This way there’s some feedback almost immediately that it’s understandable could take some time, which IMO makes for a better first-launch experience on older …
> Un-quieten vendor installs

- Library/Formula/expat.rb
Expat 2.1.0 is deprecated and has been removed from a number of mirrors. Restore working links until support for a more recent version of expat is added.
> Expat: Update URLs and HEAD

- Library/Formula/sleepwatcher.rb
SleepWatcher 2.1 and newer don't work on Tiger, but 2.0 is still provided. It requires the use of a startup item rather than launchd like the newer versions, so it's a bit different.
> sleepwatcher: Add older version which works on Tiger

- Library/Formula/jpeg.rb
For an unknown reason, the SHA256 checksum of [https://ijg.org/files/jpegsrc.v8d.tar.gz](jpegsrc.v8d.tar.gz) has changed, and as a result jpeg fails to install due to a checksum mismatch. This PR corrects that issue.
> jpeg: correct SHA256 checksum

- Library/Formula/jpeg.rb
jpeg has been updated several times since v8d in 2012, with the latest in early 2020. This updates us to the latest, which builds and runs just fine on Leopard. I've still got to test Tiger, but it seems fairly likely to be portable.
> jpeg: Update to v9d

- Library/Formula/icu4c.rb
HEAD has moved to GitHub, and some of the old file locations are gone.
> Update icu4c URLs

- Library/Formula/atk.rb
- Library/Formula/gdk-pixbuf.rb
- Library/Formula/gsettings-desktop-schemas.rb
- Library/Formula/gtk+.rb
- Library/Formula/gtk+3.rb
- Library/Formula/harfbuzz.rb
- Library/Formula/pango.rb
On Tiger, building `atk` and `gdk-pixbuf` with the system-provided `make` results in errors such as:
```
*** Need to define Atk_1_0_gir_LIBS or Atk_1_0_gir_PROGRAM.  Stop.
```
Using the brew-provided `make` fixes the issue.
> Use newer make for projects with GObject introspection

- Library/Formula/gtk+3.rb
Here are a few changes that I found necessary to compile the gtk+3 formula on 10.4.11. They are workarounds for the following facts:
* Tiger has CUPS 1.1 but not 1.2
* Tiger doesn't have the `NSTextInputClient` protocol. I am guessing this was an informal protocol prior to 10.5; it's possible that removing the protocol declaration will have a run-time effect, but in my experience Cocoa frameworks check for individual methods rather than protocol conformance. Anyway, compiling is better than not.
* Tiger's default linker doesn't find Carbon symbols (e.g. `GetCurrentButtonState`) without additional flags
> gtk+3 fixes on 10.4

- README.md
Given that GitHub has dropped support for SSL/TLS ciphers that Mac OS X 10.4 and 10.5's built-in `curl` support, the installation instructions are currently broken.
This updates the instructions to instead suggest downloading the install script with their modern computer and transferring it via the same medium they use for Xcode, which hopefully avoids some of the potential pitfalls people have experienced with TenFourFox.
> Update instructions to work around SSL troubles

- Library/Formula/imagemagick.rb
which is the last still hosted
The prior version's downloads are no longer available anywhere, and the Bintray mirror is, sadly, no longer with us.
> imagemagick: Update to latest 9.6.9 revision

- Library/Formula/zlib.rb
Building zlib with GCC 4.0 results in a static library instead of a shared library, which can cause formulae that depend on zlib (such as glib in issue #594) to fail to build.
---
Output on a 10.4.11 system without any newer GCC Tigerbrew packages installed:
```console
karen002ppc-osx104:~ karen$ brew list | grep gcc
karen002ppc-osx104:~ karen$ brew install zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to either:
brew install apple-gcc42
or:
brew install gcc
```
Output on a 10.4.11 system with applicable GCC Tigerbrew packages installed:
```console
karen002ppc-osx104:~ karen$ brew install zlib
==> Downloading http://zlib.net/zlib-1.2.11.tar.gz
Already downloaded: /Users/karen/Library/Caches/Homebrew/zlib-1.2.11.tar.gz
==> ./configure …
```
> zlib: Require building with GCC 4.2 or higher. Fixes #594.

- Library/Formula/sdl2_mixer.rb
This PR fixes the build of `sdl2_mixer`
Tested on a PowerBook G3 Pismo with Mac OS X 10.4.11. After this change, `sdl2_mixer` builds and installs no problem!
I was getting the following error when trying to build `sdl2_mixer` using `brew install -vd sdl2_mixer`:
```
libtool: compile:  /usr/local/bin/gcc-4.2 -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -F/usr/local/Frameworks -D_GNU_SOURCE=1 -D_THREAD_SAFE -I/usr/local/include/SDL2 -DHAVE_SIGNAL_H -DHAVE_SETBUF -fvisibility=hidden -DHAVE_FORK -DCMD_MUSIC -DWAV_MUSIC -DMID_MUSIC -DUSE_TIMIDITY_MIDI -I./timidity -DUSE_NATIVE_MIDI -I./native_midi -c native_midi/native_midi_macosx.c  -fno-common -DPIC -o build/.libs/native_midi_macosx.o
native_midi/native_midi_macosx.c: In function ‘native_midi_loadsong_RW’: …
```
> sdl2_mixer: patch native MIDI issue

- Library/Formula/libmagic.rb
Drop the work around for a bug in reported version URL for bug in commit is dead and new packaged version is significantly newer.
https://github.com/mistydemeo/tigerbrew/commit/eeaa5595b9540defe3b2c3ae9e6a3d183191ffe0
> libmagic: Upgrade formula to file v5.44

- Library/Formula/openssl.rb
Build tested on Tiger PowerPC
With this change `brew audit openssl` has one error flagged which is `Header files that shadow system header files were installed to "tigerbrew/Cellar/openssl/1.1.1t/include"` but unsure how to address it. Pointers appreciated if this needs to be addressed before it can be merged.
> openssl: Upgrade formula to v1.1.1u

- Library/Formula/ldns.rb
Needed to support OpenSSL version 1.1.0 and newer.
Required when PR #805 is merged
> ldns: Upgrade formula to v1.8.3

- Library/Formula/openssh.rb
Obtained from
https://github.com/Homebrew/homebrew-core/blob/e83e6ef77caf25382a7e9e85c16231361a52eee2/Formula/openssh.rb and modified slightly to drop libfido requirement for now.
Uses updated zlib from tigerbrew so depends on PR https://github.com/mistydemeo/tigerbrew/pull/809
Ideally should be merged after PR https://github.com/mistydemeo/tigerbrew/pull/805
> openssh: Add formula for v9.3p1

- Library/Formula/curl.rb
libmetalink is no longer supported
Required when PR https://github.com/mistydemeo/tigerbrew/pull/805 is merged
Uses updated zlib from tigerbrew so depends on PR #809
> curl: Upgrade formula to v8.1.2

- Library/Formula/git.rb
Git now requires pcre2, and a more recent version of make than is bundled with Tiger at least.
Use curl from tigerbrew regardless of OS version as we need to use modern openssl.
gitk now specifies a different set of colours specified in hex.
Built on Tiger with GCC 4.0 using `--with-brewed-svn --with-pcre2`
Needs #805, #810, #811, #836 and ideally #860
> git: Upgrade formula to v2.40.1

- Library/Formula/lynx.rb
Needed to support OpenSSL version 1.1.0 and newer.
Required when PR https://github.com/mistydemeo/tigerbrew/pull/805 is merged
> lynx: Update formula to v2.8.9r1

- Library/Formula/libevent.rb
Needed to support OpenSSL version 1.1.0 and newer.
Required when PR https://github.com/mistydemeo/tigerbrew/pull/805 is merged
> libevent: Upgrade formula to v2.1.12-stable

- Library/Formula/libxml2.rb
With zlib formula built as a shared library there is no linking issue
Resolves undefined symbol issue part reported in #746 
Requires PR #809 so that a shared library is available to link against.
> libxml2: Upgrade formula to v2.11.4

- Library/Formula/libxslt.rb
Disable python support since in relies on libxml2 and support is optional there.
> libxslt: Upgrade formula to v1.1.38

- Library/Formula/python3.rb
With wheel-0.38.4, pip-23.1.2, setuptools-67.8.0
There is a newer release of wheel available (0.40.0) but that uses 'flit-core' build backend and needs further work.
Dropped build head since from Python 3.11 onwards, Python requires a C11 toolchain. Python 3.10.x branch is the last release to require C99.
> python3: Upgrade formula to v3.7.16

- Library/Formula/mutt.rb
Project is no longer mercurial based and the dev.mutt.org hostname is dead.
Skip Kerberos support since updated cyrus-sasl formula disables it.
Tested with s-lang support, but not gpgme.
Requires https://github.com/mistydemeo/tigerbrew/pull/805, #871
> mutt: Upgrade formula to v2.2.10

- Library/Homebrew/software_spec.rb
Old $HOMEBREW_BOTTLE_DOMAIN redirects, so save on the roundtrip every time.
> Library/Homebrew/software_spec.rb: Save on the 301 redirect

- Library/Formula/openssh.rb
I guess the import_openssh branch here is now safe to drop?
> openssh 9.4p1

- Library/Formula/bdw-gc.rb
The 8.x branch can make use of newer pthread features but the tests don't seem to be working correctly as they pass on Tiger despite the functionality definitely not being there.
Update to the most recent 7.x release for now.
> bdw-gc: Upgrade formula to v7.6.12

- Library/Formula/ncurses.rb
The test programs are already installed as part of the initial build. Skip the test compile process.
> ncurses: Upgrade formula to v6.4

- Library/Formula/perl.rb
Deployment target needs to be set to 10.5 if -rpath is used during build.
Resolves issue #927
> Fix perl build on 10.5

- Library/Formula/qemu.rb
Previously, this formula was reverted from 2.4.x to 2.2.1 due to lockups experienced on 10.5.8 on G5. 2.3.1 runs ok for me on a G5 running Tiger.
Drop gnutls as it is dangerously out of date and disable VNC TLS support which requires it.
Allow the guest agent to be built in case OS X is virtualised.
The user mode is not enabled by default, there's no need to disable it.
Update the url for the test image with a working URL.
Built on Tiger with GCC 5
i386 hypervisor tested with
`qemu-system-i386 -cdrom some-bootable.iso`
PowerPC hypervisor tested with
`qemu-system-ppc some.iso`
Then connected to the console via VNC on localhost using [Chicken](https://sourceforge.net/projects/chicken/).
Needed the fix from PR #765
> qemu 2.3.1

- Library/Formula/tcl-tk.rb
Don't build a private copy of SQLite, use the version in Tigerbrew.
TK needs Snow Leopard at least to support Aqua, build fails due to the lack of NSMenuDelegate, NSApplicationDelegate, NSOpenSavePanelDelegate.
Fixes issue #430
Requires PR #937
Tested on
Leopard i386 & ppc, GCC 4.2
Tiger ppc, GCC 4.0.1
> tcl-tk 8.6.13

- Library/Formula/lighttpd.rb
Drop LDAP support since OpenLDAP in Leopard & Tiger lack support for ldap_distroy() which the module calls.
Provide the missing parameters for getxattr() to fix build. Provide the definition of STAILQ_FOREACH if not found in <sys/queue.h> as with Tiger.
use-ipv6 is nolonger a configurable option.
Requires #805 so should be added to the OpenSSL branch or merged after.
> lighttpd 1.4.71

- Library/Formula/gambit-scheme.rb
Make building with --enable-single-host optional since that requires a newer compiler.
Enable the dynamic-clib optimisation since the build suggests it.
By setting names, we avoid the conflict with Ghostscript. Add an option to build with OpenSSL support.
Turned off optimisation since the build process sets different optimisation flags for different components varying from O1 to O3. The build process supports more options related to compiler optimisation flags, but I did not explore any further.
Tested with GCC 4.0.1 on Tiger with OpenSSL 1.1.1u
OpenSSL support is optional, but it requires v1.1.1, so needs to be added to the OpenSSL branch for #805 or merged after if it is going to built it.
When running 'make check' there's 28 tests which fail since the unit tests try to load files from …
> gambit-scheme: Upgrade formula to v4.9.5

- Library/Formula/libsigsegv.rb
Fix test but guiding compiler to find libsigsegv to link against.
> libsigsegv: Upgrade formula to v2.14

- Library/Formula/clisp.rb
Backport fixes from git repo to fix issue with iconv macro and the lack of HTTPS support in clisp. The test suite would previously attempt to connect to the clisp website but since an HTTP->HTTPS redirect is in place now, it would trip up & the test suite run would fail.
Add fix to report an error when attempting to connect to HTTPS urls and fix the test suite to not make network connections.
Tested on Tiger with GCC 4.0.1
> clisp build fix

- Library/Formula/lz4.rb
A newer version than what was previously offered in the formula is required for current version of subversion.
> lz4: Upgrade formula to r193

- Library/Formula/nettle.rb
Turn off compiler optimisation as tests fail.
Always use OpenSSL from brew.
Test example needs to find libnettle to build.
Test suite needs a newer compiler that GCC 4.0.1. Works fine with GCC 5.5. Nettle itself builds and installs just fine with GCC 4.0.1 however.
Requires #805  so should be added to the OpenSSL branch or merged after that branch has landed
> nettle: Upgrade formula to v3.9.1

- Library/Formula/utf8proc.rb
Based on
https://raw.githubusercontent.com/Homebrew/homebrew-core/05399d9c3f9ffd0a1424431c34acfe3ab279d477/Formula/utf8proc.rb Test has been changed since strnlen() is not available Simplify test so version doesn't need to be maintained Set standard to C99 to avoid having to return something, since GCC 4.0 defaults to C89 and complains.
Required for new versions of tmux.
> utf8proc: Add formula for v2.8.0

- Library/Formula/tmux.rb
It is now mandatory to specify whether utf8proc support is enabled or not.
Requires #894
> tmux: Upgrade formula to v3.3a

- Library/Formula/p11-kit.rb
Newer versions from 0.25.0 have a strnlen(3) dep which Tiger & Leopard certainly lack.
> p11-kit: Upgrade formula to v0.24.1

- Library/Formula/gnu-tar.rb
v1.35 which is currently the latest version includes a new version of gnulib which no longer builds on Tiger without additional support from another library, so stick with v1.34 for now.
> gnu-tar: Upgrade formula to v1.34

- Library/Formula/graphviz.rb
v2.46.0 is the last version before C++11 support became a requirement. Drop building Quartz support on Tiger as support is lacking. Quartz support is enabled on Leopard and newer due to when Availability.h first landed which the plugin includes and has not been build tested.
> graphviz: Upgrade formula to v2.46.0

- Library/Formula/pcre.rb
PCRE is now EoL (pcre2 is where development happens), so drop support from building from head of branch.
> pcre: Upgrade formula to v8.45

- Library/Formula/vala.rb
Need libxslt since the version shipped with OS is likely out of date & the build breaks.
Requires #887, #888
> vala: Upgrade formula to v0.56.9

- Library/Formula/cmake.rb
From v3.10 onwards cmake enforces the requirement of a C++11 compiler. Python modules have been upgraded to latest version to support Python 2.7 or most recent version required by cmake itself e.g docutils. Switched cmake build to use libraries provided via Tigerbrew. Given up to date formulas, the build of cmake itself is faster since it skips on building its own private copies of libraries which are now quite old as well.
> cmake: Upgrade formula to v3.9.6

- Library/Formula/libtiff.rb
Enable support for lzma compression.
Use zlib formula, since libtiff is extremely prone to security issues and OS supplied version is ancient.
Requires PR #809 and ideally #841
> libtiff: Upgrade formula to v4.5.0

- Library/Formula/mksh.rb
"The options combine and lto were removed, as link-time optimisation has proven to be too fragile in compilers."
> mksh: Upgrade formula to R59c

- Library/Formula/zlib.rb
This PR corrects the URL for zlib source code. The URL without the fossils/ folder only works for the latest release.
> Fix zlib URL to point to fossils/ folder

- Library/Formula/ld64.rb
openssl formula is now key only so users upgrading from v1.0.0 to v1.1.1 ended up with a broken ld since it links to libcrypto for MD5 support on Tiger.
Fixes #943
> ld64 Add OpenSSL dependency

- Library/Formula/retroforth.rb
Need to use a compiler with C11 type redefinition support such as GCC 4.6 or newer.
Tested with GCC 5
`brew install --cc=gcc-5 retroforth`
> retroforth: Add formula for v2023.3

- Library/Formula/muttils.rb
After v1.4, head dropped Python 2 support and now requires 3.8 min.
Since we currently package 3.7, drop support for building head for now.
> muttils: Upgrade formula to v1.4

- Library/Formula/pixman.rb
TODO:
The code in the test section works, and completes successfully. The test is considered a failure by brew though as pixman_image_unref() returns a boolean value where true is successful, and brew expects a zero (false).
> pixman: Upgrade formula to v0.42.2

- Library/Formula/nginx.rb
Switch from PCRE to PCRE2 as that former is EoL.
Avoid using the OS supplied zlib
Build HTTP/2 support by default as it's standardised, introduce HTTP/3 support as an option in its place which is now experimental.
Needs PR #805
> nginx: Upgrade formula to v1.25.2

- Library/Formula/libelf.rb
Website is defunct, taking the source archive with it.
Resolves  #802
> libelf: Fix urls

- Library/Formula/scons.rb
v3.1.2 is the last version to support Python 2 (v4 requires Python 3).
With this version of scons, serf links without issue on Tiger with GCC 4.0. Avoiding a toolchain upgrade. https://github.com/mistydemeo/tigerbrew/issues/333
> scons: Upgrade formula to v3.1.2

- Library/Formula/subversion.rb
Along with serf 1.3.9
There currently isn't a formula for utf8proc so the internal implementation is used.
Ideally should be merged after PR #814 #815 to upgrade apr and apr-utils, #816 #817 are requirements.
With these updates, it's possible to build subversion on Tiger with stock GCC 4.0, avoiding linker/compiler upgrade.
> subversion: Upgrade formula to v1.14.2

- Library/Formula/gcc5.rb
[GCC Bug 25127](https://gcc.gnu.org/bugzilla//show_bug.cgi?id=25127) is something to beware of, as discussed in issue  #152.
Affects building on both Tiger & Leopard.
Workaround is to not use CPU optimisation flags.
Built with #855, #856, #857
> gcc5: Upgrade formula to v5.5

- Library/Formula/gcc5.rb
Builds on G4/Intel Tiger/Leopard.
> gcc5: update to 5.5.0, fix build on Intel Tiger

- Library/Formula/gcc6.rb
Builds on G4/Intel Tiger/Leopard.
> gcc6: update to 6.4.0, fix build on Intel Tiger

- Library/Formula/openconnect.rb
Use latest vpnc-script
Switch back to using OpenSSL now that it is up to date (gnutls isn't and it requires C11 support).
Fix test
Build tested on Tiger powerpc with GCC 4.0.1, haven't tried to establish a VPN connection to a supported appliance.
> openconnect 9.12

- Library/Formula/wget.rb
v1.21.4 includes the latest version of gnulib which is incompatible with Tiger, requiring integration with libsigsegv.
Stick with this version for now which is sufficient for building against current OpenSSL.
> wget 1.21.3

- Library/Formula/openssh.rb
Not bumping package revision as it only affects new build attempts, post zlib 1.3 install.
Resolves issue #965
> openssh Fix zlib version check for >= 1.3

- Library/Formula/openssl.rb
Build tested on OS X Tiger with GCC 4.0.1.
This is the last release of OpenSSL 1.1.1, development continues in v3.x.
> openssl 1.1.1w

- Library/Formula/openssl3.rb
OpenSSL v1.x.x will soon be EoL, in prep, add a formula for v3.
Though nothing is currently pointed to it as a dependency, it paves the way should someone wish to.
Based on
https://github.com/Homebrew/homebrew-core/blob/bdf52e4896818e57839a8110779b8dad97fe505c/Formula/openssl%403.rb
Currently lacks the ability to support ppc64 because I don't know how to Ruby and handle arch_args, so currently only 32bit builds are supported on ppc.
> openssl3: Add formula for v3.1.2

- Library/Formula/gcc.rb
- Library/Formula/gcc5.rb
- Library/Formula/gcc6.rb
Don't enable plugin support on Leopard as it doesn't work.
Fixes #518, again.
> Fix GCC build regression on Leopard

- Library/Formula/vim.rb
NSSoundDelegate apparently was introduced in Snow Leopard yet the build breaks on it. Guarding off enabling sound support to El Capitan as that's the next version I had access to for testing. https://developer.apple.com/documentation/appkit/nssounddelegate
Tested on Tiger powerpc with GCC 4.0.1, Snow Leopard with GCC 4.2, El Capitan with llvm from XCode 7.
> vim 9.0.1907

- Library/Formula/fennel.rb
Based on
https://github.com/Homebrew/homebrew-core/blob/84521a58ec3789c7e1268e050d999bc72b428646/Formula/f/fennel.rb
Requires #969
> fennel 1.3.1

- Library/Formula/openssl.rb
- Library/Formula/openssl3.rb
Skipping version bump as they would not have built on x86 in the first place.
> openssl x86 & Snow Leopard fixes

- Library/Formula/gmp.rb
Tested on Snow Leopard (x86) with gcc 4.2
Resolves #977
> gmp x86_64 assembler fix

- Library/Formula/git.rb
Set anything before Lion (Darwin 11) to NO_REGEX otherwise build breaks as REG_ENHANCED is not defined as not supported.
This may need bumping again, as I haven't tested on Lion.
Tested on Tiger PowerPC & Snow Leopard x86.
Resolves #978
> git Snow Leopard fix

- Library/Formula/curl.rb
- Library/Formula/dovecot.rb
- Library/Formula/gambit-scheme.rb
- Library/Formula/git.rb
- Library/Formula/irssi.rb
- Library/Formula/ldns.rb
- Library/Formula/libevent.rb
- Library/Formula/libssh2.rb
- Library/Formula/lynx.rb
- Library/Formula/midnight-commander.rb
- Library/Formula/mutt.rb
- Library/Formula/nginx.rb
- Library/Formula/ntp.rb
- Library/Formula/openconnect.rb
- Library/Formula/openssh.rb
- Library/Formula/postgresql.rb
- Library/Formula/rsync.rb
Start switching formulas to openssl3 now that openssl 1.1.1 is EoL.
Ideally should be merged after the openssl3 update in #981
Libraries such as ldns, libevent, libssh2 should be built first, before applications, otherwise openssl 1.1.1 creeps in as a dependency.
> openssl3 switch

- Library/Formula/av98.rb
There's now a dedicated geminiprotocol.net domain.
Use that for testing instead.
> av98: Update test target hostname

- Library/Formula/rancid.rb
Use git instead of CVS.
Though git is a runtime dep, configure checks for git.
Tested on Tiger.
> rancid 3.13

- Library/Formula/mpfr.rb
Fix test target.
Tested on Tiger (g4/g5) with GCC 4.0.1, Leopard (g4/intel) with GCC 4.2, Snow Leopard (intel) with gcc & llvm-gcc
Should be merged after #992
> mpfr 4.2.1

- Library/Formula/libtiff.rb
Drop --without-x as it is now unrecognised.
> libtiff 4.6.0

- Library/Formula/giflib.rb
Include patch to Makefile inline since we also need to allow CFLAGS to be overriden, otherwise build breaks with GCC 4.0 since -Wno-format-truncation is not supported.
> giflib 5.2.1

- Library/Formula/webp.rb
Build with GIF, JPEG, TIFF support by default since they are lightweight build dependencies and it's no loss.
Should be merged after #1016 and #1017
> webp 1.3.2

- Library/Formula/giflib.rb
Fixes the build on Leopard.
Fixes #1020.
> giflib: explicitly pass CFLAGS

- Library/Formula/gnu-cobol.rb
Tested on Tiger (G5) with GCC 4.0.1 & GCC 5.5.
The configure script does the right thing and we don't need pass in `--with-cc`
> gnu-cobol 3.2

- Library/Formula/gforth.rb
> gforth: Add mirror url

- Library/Formula/libtool.rb
Just as a heads up, the builds compiler name is embedded in the `glibtool` script and if that version is not installed, it breaks since `glibtool` tries to invoke that compiler. e.g `gcc-4.2`. Might be worth bottling using 4.0.1 as that will always be installed.
> libtool 2.4.7

- Library/Formula/expect.rb
Based on
https://github.com/Homebrew/homebrew-core/blob/ec1fa2144b72b90370eeccec27e8743acdb86bf7/Formula/e/expect.rb
> expect: Add formula for v5.45.4

- Library/Formula/glib.rb
v2.59.0 is the last version to support autoconf'd builds. Project switched to Meson builds from there on.
I have dropped universal build support patches.
Built with GCC 4.0 on Tiger.
> glib 2.59.0

- Library/Formula/swig.rb
Switch to using pcre2 as pcre is EoL
> swig: Upgrade formula to v4.1.1

- Library/Formula/gobject-introspection.rb
v1.60.2 is the last version to support autoconf.
More recent versions require meson.
> gobject-introspection: Upgrade formula to v1.60.2

- Library/Formula/json-glib.rb
v1.2.8 is the last version to support autoconf.
More recent versions require meson.
Require up to date make as older version in Tiger is unable to build.
Resolves #804 
Ideally should be merged after PR #846
> json-glib: Upgrade formula to v1.2.8

- Library/Formula/libidn2.rb
Based on
https://github.com/Homebrew/homebrew-core/commit/f15b1c5e2bad1c6735da8657300010ef406e0c23
Tested on Tiger (g5) with GCC 4.0.1
This has a libunistring dependency which has a couple of issues with its tests that I haven't resolved yet (I skipped the make check stage to get the dependency installed).
> libidn2: Add formula for v2.3.4

- Library/Formula/libxcrypt.rb
Based on
https://github.com/Homebrew/homebrew-core/commit/3c284f6aa8beaa9db2ca162602580c1cd8b023dd
Tested on Tiger (g5) with GCC 4.0.1
> libxcrypt: Add formula for v4.4.36

- Library/Formula/mandoc.rb
Use the default names for utilities, it very much is ready for prime-time on Darwin.
HOMEBREWDIR has been renamed to READ_ALLOWED_PATH
There is no manpage target now.
Built on Tiger (G5) with GCC 4.0.1
> mandoc 1.14.6

- Library/Formula/mercurial.rb
Add gettext as a build dep to get translations
warning: hgbuildmo: could not find msgfmt executable, no translations will be built.
Tested on Tiger (G5) with GCC 4.01
> mercurial 6.6

- Library/Formula/autoconf.rb
Tested on Tiger (G5) with GCC 4.0.1 .
Now need a more recent version of m4 than the again GPLv2 version of m4 shipped with all version of macos.
> autoconf 2.72

- Library/Formula/libssh2.rb
Tested on Tiger (G5) with GCC 4.0.1 .
> libssh2: CVE-2023-48795 fix

- Library/Formula/libnghttp2.rb
Tested on Tiger (G5) with GCC 4.0.1 as a dependency for curl.
based on
https://github.com/Homebrew/homebrew-core/blob/d60bc504f4526917b7aae5cdae51f188edcc7d8e/Formula/lib/libnghttp2.rb
> libnghttp2: Add formula for v1.58.0

- Library/Formula/curl.rb
Enable HTTP/2 support by default using libnghttp2 as it is a light dependency, buildable with GCC 4.0.1, whereas the full nghttp2 needs a minimum of GCC 6 to build its C++ components.
Tested on Tiger (G5) with GCC 4.0.1 .
> curl 8.5.0

- Library/Formula/fatsort.rb
The support for PowerPC seems to be dropped for this useful tool. I went to sourceforge and compiled all the versions until I found the last one working on my Mac Os X Leopard and tested the install successfully.
> fatsort 1.5.tbd

- Library/Formula/openssl.rb
makedepend is slow and the compiler is capable of handling dependencies.
If you have makedepend installed, you should uninstall it on Tiger as we're not guarded against using it and build will take a little longer.
Discovered when investigating why a G4 iBook running Leopard was taking less time than a G5 iMac running Tiger.
Build on iBook G4 with Leopard 39.5 minutes
Build on iMac G5 with Tiger  32.2 minutes
> openssl: drop makedepend build dep

- Library/Formula/gettext.rb
This is a biggy since it impacts a lot of packages.
I've built and tested on Tiger with GCC 4.0.1, Leopard GCC 4.2, Snow Leopard, El Capitan clang.
> gettext 0.22.4

- Library/Formula/git.rb
Needs a minimum of 10.10 Yosemite.
Fix building on Lion too, by bumping the version for enhanced regex support.
Tested on 10.4, 10.6 to 10.11 and confirmed FSMonitor support is enabled in 10.10 & 10.11.
Closes #1053
> git: Adjust guard for FSMonitor support

- Library/Formula/bdw-gc.rb
libatomic_ops is included in the library list of bdw-gc.pc, if it's not installed, consumer's build breaks.
> bdw-gc: Adjust libatomic_ops dep

- Library/Formula/utf8proc.rb
Built on Tiger (G5) with gcc 4.0.1, Leopard (G4) with gcc 4.2, Snow Leopard, El Capitan with clang.
> utf8proc 2.9.0

- Library/Formula/libftdi.rb
> libftdi: Need to enable warnings for GCC 4.0

- Library/Formula/gnutls.rb
p11-kit is no longer optional
Skip touching anything to do with the certificates in system supplied keychains as they'll most definitely be out of date now. Use up to date zlib instead of the system provided one.
Tested on Tiger (G5) with GCC 5.5 & GCC 7 (needs a C/C++ 11 compiler).
Should be built after PR #1031 is merged
I haven't dealt with the revision bump as previously stated in the top comment (now removed since it was about the then incoming 3.4 release)
> gnutls 3.7.10

- Library/Formula/whois.rb
Based on
https://raw.githubusercontent.com/Homebrew/homebrew-core/f04bca02643e44e5fa8b9fd5aaff131a4d1821b3/Formula/w/whois.rb
Rather that build & copy selected binaries in the original formula, we 'make install' which is where the bash-completion dependency comes in. Opted to add the dependency, rather than patch the Makefile which calls pkg-config to work out where to install bash-completions.
Requires PR #997, #998, #1024 
> whois: Add formula for v5.5.20

- Library/Formula/liblinear.rb
- Library/Formula/nmap.rb
Tested on G5 running Tiger with GCC 5.5.
nmap needs newer C++ support than apple-gcc 4.2 & 4.0 offer.
Included the liblinear update in this commit since it is a dependency that's also a C++ project however it'll happily build with GCC 4.0.
Had to resort to a bodge with sed since configure is patched locally & remotely (via github commit patches), they can hopefully be dropped with the next release of nmap.
> nmap 7.94 & liblinear 2.47

- Library/Formula/aspell.rb
Update dictionaries using https://ftp.gnu.org/gnu/aspell/dict/0index.html
Disable `is` & `nb` dictionaries as tar struggles with the archives
```
/usr/bin/tar: aspell-is-0.51.1-0/\355slenska.alias: Cannot open: Invalid argument
/usr/bin/tar: aspell-nb-0.50.1-0/bokm\345l.alias: Cannot open: Invalid argument
```
> aspell 0.60.8

- Library/Formula/libffi.rb
For some reason, libffi's formula had a bad path specification in its test method.  This small change fixes it.
> unbreak `brew test libffi`

- Library/Formula/id3ed.rb
Assist with finding libhistory and ensure tigerbrew's readline is used.
> id3ed: build fix

- Library/Formula/python3.rb
tcl-tk requires X11 on Tiger and the Python's tkinter module struggles to interact with legacy TCL/TK included with Tiger which has Aqua bindings. So always use the tcl-tk version from tigerbrew.
Use bzip2 from tigerbrew to avoid ancient bundled versions.
> python 3.10.14

- Library/Formula/openssh.rb
It had been using a method call from upstream Homebrew.  I copied the few lines of actual meat into the test routine and it seems to work fine now.
> openssh: fixed the test

- Library/Formula/tcpdump.rb
Based on
https://raw.githubusercontent.com/Homebrew/homebrew-core/64ccd322494a17aa83fd3f815fc75cfed31dfacd/Formula/t/tcpdump.rb
> tcpdump: Add formula for v4.99.4

- Library/Formula/openvpn.rb
`enable-password-save` is no longer a recognised `configure` option.
Switch to using openssl3
Build tested on Tiger powerpc (G5) with GCC 4.0.1
> openvpn 2.6.10

- Library/Formula/imagesnap.rb
Imagesnap's list of valid architectures only includes i386 and x86_64. However, it compiles and works fine in PowerPC. This change adds the ppc and ppc64 architectures in the build invocation.
> Fix imagesnap for ppc

- Library/Formula/nano.rb
Like vim formula not marked as keg_only though a version is included with OS X.
Based on
https://raw.githubusercontent.com/Homebrew/homebrew-core/017421c494107b35d3a519c93ace9c8f42235a3d/Formula/n/nano.rb
> nano: Add formula for v8.0

- Library/Formula/teensy_loader_cli.rb
Tested on Tiger powerpc (G5) with GCC 4.0.1 and a Teensy 2
```
bin/teensy_loader_cli -w --mcu=TEENSY2 /tmp/teensy_loader_cli-2.2/blink_slow_Teensy2.hex -v
Teensy Loader, Command Line, Version 2.2
Read "/tmp/teensy_loader_cli-2.2/blink_slow_Teensy2.hex": 2332 bytes, 7.2% usage
Waiting for Teensy device...
(hint: press the reset button)
Found HalfKay Bootloader
Read "/tmp/teensy_loader_cli-2.2/blink_slow_Teensy2.hex": 2332 bytes, 7.2% usage
Programming...................
Booting
```
> teensy_loader_cli 2.2

- Library/Formula/open-vcdiff.rb
--disable-debug is not a configure option
> open-vcdiff: fix homepage

- Library/Formula/z80dasm.rb
Homepage is offline for now and the src was not on archive.org
Add a source mirror.
> z80dasm 1.2.0

- Library/Formula/geoip.rb
Make sure the GeoIP.dat file is installed so geoiplookup tools work.
Fix test.
Skip the legacy path migration as it is redundant now.
No need to re-autoconf any more.
Tested on Tiger powerpc (G5) with GCC 4.0.1, Snow Leopard with GCC 4.2
> geoip 1.6.12

- Library/Formula/libarchive.rb
Use up to date libraries from Tigerbrew as dependencies
Build only checks for the presence of `sys/queue.h` and not whether the actual required macros are defined. 
Use the up to date copy of queue.h included in libarchive instead.
Should be merged after #1077
> libarchive 3.7.4

- Library/Formula/libdc1394.rb
Build tested only on Tiger powerpc (G5) with GCC 4.0.1 & 4.2.
Supports USB & Firewire cameras despite name.
> libdc1394 2.2.6

- Library/Formula/smartmontools.rb
Tested on Tiger powerpc (G5) with GCC 5.5 & 7.5. `smartctl -a /dev/disk0` provided the SMART info for my SATA disk.
> smartmontools 7.4

- Library/Formula/openssh.rb
This currently doesn't work for me - I'm getting errors at runtime.
This reverts commit f3e6b1f425f2664682596efa18aea9c2d0747a50.
> revert openssh 9.8p1

- Library/Formula/macvim.rb
Reference reported issue [here](https://github.com/mistydemeo/tigerbrew/issues/1189#issue-2523049346).
brew update was run prior to the attempt to install MacVim.
brew doctor doesn't report any issues.
Attempting brew install macvim results in the following error:
```bash
Error: SHA256 mismatch
Expected: 6b7f4b48ecef4a00dca17efef551884fcea1aa9897005497d31f52da7304bc5f
Actual: 4696b2cd6f69093c8a619daee9a0db441ce1a124edfddd3b0b3fed3ac96f8e8d
```
Downloading the snapshot file manually and calculating the sha256 hash reveals the correct checksum matches the actual reported by Tigerbrew.
```bash
$ sha256sum snapshot-77.tar.gz 
4696b2cd6f69093c8a619daee9a0db441ce1a124edfddd3b0b3fed3ac96f8e8d  snapshot-77.tar.gz
```
> macvim 7.4-77 bugfix

- Library/Formula/openssl.rb
Ensure makedepend is never used as it slows down the build considerably.
For PowerPC builds OpenSSL already applies -fno-common automatically but opted to pass it conditionally here to avoid having to patch OpenSSL.
as(1) for Tiger/Intel only recognises ".comm name, size", not ".com name, size, alignment" We're also building with no-common and the assembly files use the common directive. :/
> openssl: Tiger/Intel build fixes

- Library/Formula/openssl3.rb
It's now possible to build on Tiger with asm support. `OPENSSL_LOCAL_CONFIG_DIR` landed in OpenSSL 1.1.0 and we've building with it untouched in `openssl.rb`, don't bother unsetting it here too.
Skip setting compiler optimisation, the build ends up setting -O3 in places.
By making the test suite run optional, and only installing manuals, build time is significantly reduced.
120minutes before (full docs, suite run) to
no test, with docs, 35.9 minutes
no test, with man, 29.3
Building no tests, no docs results in 19.5mins on 1.8Ghz G5 iMac.
224 minutes with tests & man, 44minutes no tests, with  man, on a 1.33Ghz G4 PowerBook.
50.5 minutes no tests, with man, on a 1.33Ghz iBook G4
Tested on Tiger powerpc (G4/G5) and intel (core2duo) with GCC 4.0.1, Leopard powerpc (G4) and intel (core2duo) …
> openssl 3.4.0

- Library/Formula/libksba.rb
> libksba 1.6.7

- Library/Formula/pinentry.rb
Disabled fltk gui support as that requires C++11 support so the build goes from doing fine with GCC 4.0.1 to failing as soon as hits the fltk support part.
> pinentry 1.3.1

- Library/Formula/rhash.rb
Tested on Tiger (G5) with GCC 4.0.1 and Snow Leopard with GCC 4.2
> rhash 1.4.5

- Library/Formula/libpsl.rb
Since it's going to be for security around cookies, best to make use of up to date dependencies from Tigerbrew.
https://daniel.haxx.se/blog/2024/01/10/psl-in-curl/
Should be merged after #1196
> libpsl: Add formula for v0.21.5

- Library/Formula/curl.rb
Curl now requires libpsl for security around cookies to build.
https://daniel.haxx.se/blog/2024/01/10/psl-in-curl/
Needs #1198 to be merged before.
Ideally should be merged after #1037, #1182
> curl 8.10.1

- Library/Formula/ld64.rb
Saves a detour into building OpenSSL + deps when version included with OS is sufficient for providing MD5 support.
Tested on Tiger (G5) with GCC 4.2, then built `cctools` which depends on `ld64`
Not sure if a revbump is needed as it will create churn, really beneficial for those on G3 based systems, starting out, who do not get prebuilt packages in the first place.
```
Cellar/ld64/97.17_1/bin/ld:
/usr/lib/libcrypto.0.9.7.dylib (compatibility version 0.9.7, current version 0.9.7)
/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.1.12)
```
> ld64: Use OpenSSL included with OS

- Library/Formula/recode.rb
Switch to a fork which is actively maintained.
The original repo hasn't been touched in some years and has build issues.
This fork is also used by MacPorts.
Tested on Tiger (G5) with GCC 5.
> recode 3.7.14

- Library/Formula/xvid.rb
Fix urls reported in issue #1194
Enable assembly support, xvid support Altivec & Intel CPU extensions. The configure stage makes all the right noises about endiannes/arch/OS regarding assembly support. Compile tested only.
Fix test otherwise GCC 4.0 complains about compiling C++.
On Tiger/Intel it won't enable assembly as
configure: WARNING: nasm version is too old
configure: WARNING: no correct assembler was found - Compiling generic sources only
Tested on Tiger (G5/core2duo) with GCC 4.0, core2duo only: GCC 4.2
> xvid 1.3.7

- Library/Formula/wget.rb
Build with IDN and PCRE support by default.
Make use of pkg-config support for finding dependencies Missed out switching from openssl to openssl3 in configure last time. Adjust test so that it doesn't output to stdout and use a lighter target.
Should be merged after #1037 and #1196.
> wget 1.25.0

- Library/Formula/openssh.rb
Drop the sandbox patches since with the further process separation changes which landed in v9.8, sshd breaks.
macOS 10+5 ships with v9.8 and the source drop also shows they are no longer applying these patches.
See OpenSSH-341 sources:
https://github.com/apple-oss-distributions/OpenSSH/tree/OpenSSH-341/
Tested on Tiger powerpc (G5) with GCC 4.0.1, Leopard powerpc (G4) with GCC 4.2
> openssh 9.9p1

- Library/Formula/freeipmi.rb
Compile tested on Tiger powerpc (G5) with GCC 4.0.1
> freeipmi 1.6.14

- Library/Formula/git.rb
git-credential-osxkeychain needs Lion or newer so drop the patch.
regen config.mak.uname patch so it applies again.
> git 2.47.1

- Library/Formula/confuse.rb
> confuse 3.0

- Library/Formula/libftdi.rb
Built without C++ support since the C implementaton will build with
a C99 compiler but the C++ parts require a C++11 compiler.
Needs #1079 & #1066
> libftdi 1.5

- Library/Formula/sphinx.rb
This is the last release version of Sphinx which sources are readily available.
For the security patches, I had to set the types for sNormalized & iChunkLen otherwise build fails with `ISO C++ forbids declaration of ‘bla’ with no type`
Resolves #1088
> sphinx 2.2.11

- Library/Formula/openfpgaloader.rb
Based on
https://raw.githubusercontent.com/Homebrew/homebrew-core/4193b47068bd44bba3f18fb1f9f66bdc9fcef66b/Formula/o/openfpgaloader.rb
Tested detection with a Sipeed Tang Nano 9k & a Terrasic DE0-nano on Tiger powerpc (G5) + GCC 5.5.
> openfpgaloader: Add formula for v0.11.0

- Library/Formula/avrdude.rb
v7.0 is the last autoconf'd version of avrdude, newer versions switch to cmake & require a newer version than we package. Switch to using libftdi 1.x as it is the actively developed release branch.
Tested on Tiger powerpc G4/GCC 7.5 and G5/GCC 5.5, libftid 0.20 & 1.1 and a [littlewire adapter](http://littlewire.github.io).
Requires PR #1064 #1066
> avrdude 7.0

- Library/Formula/vala.rb
It masks an issue with glib's `pkg-config` file which is parsed at runtime by `valac`. `glib-2.0.pc` should have the relevant parts for `-lintl`.
See PR #1029
> vala: Don't assist with path for libintl

- Library/Formula/python3.rb
Skipping upgrading pip as setup.py was removed in the following release. Expectation is ensurepip module is used now with the newer releases. Add gettext as dependency since version included in 10.5 is missing symbols
Undefined symbols:
"_libintl_textdomain", referenced from:
__locale_textdomain in libpython3.10.a(_localemodule.o)
"_libintl_dgettext", referenced from:
__locale_dgettext in libpython3.10.a(_localemodule.o)
"_libintl_dcgettext", referenced from:
__locale_dcgettext in libpython3.10.a(_localemodule.o)
"_libintl_bindtextdomain", referenced from:
__locale_bindtextdomain in libpython3.10.a(_localemodule.o)
"_libintl_gettext", referenced from:
__locale_gettext in libpython3.10.a(_localemodule.o)
Tested on Tiger (G5/c2d) with GCC 4.0.1, Leopard (G4) with GCC 4.2
> python 3.10.16

- Library/Formula/libtiff.rb
GCC 4.0 lacks ___builtin_bswap32()
ld: Undefined symbols:
___builtin_bswap32
Tested on Tiger (c2d) with GCC 4.2
> libtiff: Don't use GCC 4.0 on Tiger/intel

- Library/Formula/libffi.rb
as(1) & GCC 4.0 included in XCode 2.5 are insufficient to handle the x86 assembly in src/x86/sysv.S on Tiger/intel, need to use cctools with GCC 4.2.
Tested on Tiger G5 with GCC 4.0 and c2d with GCC 4.2.
This should be bottled before the python update in #1225, made a mistake in order.
> libffi 3.4.5

- Library/Formula/capstone.rb
Does not like build built with GCC 4.2 but happy with 4.0 & clang.
Tested v5.0.1 on Tiger (G5) & Leopard & Snow Leopard (intel) with GCC 4.0.1, El Capitan with clang
Tested v5.0.3 on Tiger (G5) with GCC 4.0.1
> capstone 5.0.3

- Library/Formula/qt.rb
Need to build with Carbon support.
Ride the default with qt3support as it might be handy. Since it's a lengthy build, the previous option didn't work and failed on install stage. Add sqlite support so at least there is some database support by default.
draft since ~there is a bodge patch to src/corelib/io/qfilesystemengine.cpp,~ I need to enable building with OpenSSL 1.1.1, ~I haven't tested on anything beyond Tiger~.
~When it is ready to land, the PRs 529 575 577 should be reviewed to see if there's any additional bits that should be integrated.~ This PR basically introduces the changes proposed in PR 529 + fixes the issue building QtHelp & qmake on Tiger.
Skipping building with OpenSSL 1.1.1 as the patches I found were for 1.1.0 and more things need guarding off regarding to OpenSSL API …
> qt: Fix build on Tiger

- Library/Formula/mipscope.rb
Needs QT4, PR #1154 
Tested on Tiger powerpc (G5/i386) with GCC 4.0.1, Leopard powerpc (G5/i386) with GCC 4.2, Snow Leopard (x86_64) with GCC 4.2, El Capitan with clang.
> mipscope: Add formula for v0.3.3

- Library/Homebrew/language/python.rb
With the recent upgrade from Python 3.7 to 3.10 the minor version needs to be double digits.
Taken from upstream
https://github.com/Homebrew/brew/commit/a1efaf1864049977d7d90f32e5ff1e897cf57d96#diff-7e7f927b5a956040b1e5cd4fc54be50d29778145d2cfd57cd1598ed3823e95c0R54
Tested change by installing `internetarchive` module using `pip2` & `pip3`
> python major_minor_version() fix

- Library/Formula/cython.rb
Based on
https://github.com/Homebrew/homebrew-core/blob/64ccd322494a17aa83fd3f815fc75cfed31dfacd/Formula/c/cython.rb
Tested on Tiger powerpc (G5) with GCC 4.0.1 and Python 3.10
Requires #1228
> cython: Add formula for v3.0.11

- Library/Formula/flashrom.rb
Build tested (I don't think I have any supported hardware at hand) on Tiger (G5) with GCC 5.5
It's likely that flashrom can be compiled with GCC 4.0 but there's a huge struct with an re-occuring issue that GCC 4.0/42 don't like.
Should be merged after https://github.com/mistydemeo/tigerbrew/pull/1066
> flashrom 1.4.0

- Library/Formula/pcre2.rb
Don't enable JIT, we actually worked on PowerPC support and got it passing the test suite fully, however there appears to be a regression.
Tested on Tiger (G5/i386) with GCC 4.0.1.
> pcre2 10.44

- Library/Formula/libressl.rb
Avoid building with CPU optimisation as 4 tests fail when running test suite during 'make check'
Re-enable building with asm as issue was fixed as merged in. https://github.com/libressl/portable/issues/121#issuecomment-139546026
> libressl: Upgrade formula to v4.0.0

- Library/Formula/gettext.rb
Via Macports
https://raw.githubusercontent.com/macports/macports-ports/dc7e04359c5c10cd854d5ec79dab534a508d5024/devel/gettext/files/has_attribute.patch
Use llvm-gcc on 10.7 & 10.8, fixes issue #1053 on 10.8, without having to explicitly specify a compiler until the issue is address in gnulib.
> gettext: 10.7 - 10.9 build fixes

- Library/Formula/automake.rb
Use test obtained from upstream.
https://github.com/Homebrew/homebrew-core/blob/79dd816d010092bf95d5d154d3ac23366b1a6e5e/Formula/a/automake.rb
> automake 1.17

- Library/Formula/git.rb
> git 2.48.0

- Library/Formula/rhash.rb
- Library/Homebrew/version.rb
Looks like we both missed that rhash lost its unversioned `librhash.dylib` with the patch changes in the 1.4.5 update. Only noticed when cmake had trouble finding it.
> rhash: restore missing symlink

- Library/Formula/libvorbis.rb
Tested on Tiger (G5/G4/i386) with GCC 4.0.1, Leopard (G4/i386) with GCC 4.2, 10.6 (i386) to 10.11 with default compiler (not llvm-gcc where applicable)
> libvorbis 1.3.7

- Library/Formula/libtool.rb
For consistency, just depend on m4.
Add test from upstream
https://github.com/Homebrew/homebrew-core/blob/ba0b94f04555ff631772bd974b337436fabdccfb/Formula/lib/libtool.rb
Tested on Tiger PowerPC (G5) with GCC 4.0.1, Leopard i386 with GCC 4.2, Snow Leopard with GCC 4.2, El Capitan with clang.
> libtool 2.5.4

- Library/Homebrew/extend/ENV/super.rb
$M4 is set to the version which ships with OS X, and when it comes to configuring automake, autoconf is tested which invokes the version of M4 included in OS X due to the variable being set and fails as m4 is too old and doesn't recognise --gnu to enable GNU extensions.
Upstream dropped the variable[1] for exactly this reason, and then reintroduce it to cover when libtool is involved[2] to prevent libtool from using the m4 shipped with OS X for the opposite reason ($M4 is not set, traverse $PATH to find m4).
Confirmed dropping the variable resolves the automake build on 10.5 to 10.11 (tested 10.4 too but it never was an issue there).
[1] https://github.com/Homebrew/brew/commit/f6eba3c1ea2c5ac069b667d45e39b739366e2ed6
[2] https://github.com/Homebrew/brew/commit/e8452de418b3ec7ac2864a5384d7e …
> autoconf: Unbreak on Leopard & up

- Library/Formula/libftdi.rb
Noticed the build broke for GCC 4.2 on Tiger, but we have this fix in a couple places. Longer-term, might be worth seeing if this actually belongs in `std_cmake_args` itself.
> libftdi: fix build with gcc-4.2/Tiger

- Library/Formula/qt.rb
@sevan Not sure if you tested with GCC 4.2 on Tiger, or just 4.0 - wanted to double check if this lines up with what you'd seen.
> qt: fails with gcc-4.2 on Tiger

- Library/Formula/pilot-link.rb
Marking as daft because it needs more testing.
Works fine on Tiger because there's no native drivers for USB sync, but on Leopard there is and trying to access the device via `libusb` fails. Need to make that conditional for when on Tiger & test some more, then it can land.
> pilot-link: Add formula for v0.12.5

- Library/Formula/git.rb
It works fine if built with GCC 4.0.
Fixes #1250.
> git: avoid gcc-4.2 on Tiger

- Library/Formula/popt.rb
`alignof()` is undefined and results in a build failure with clang.
Tested on 10.7/10.8/10.9. 10.9 built fine with clang.
> popt: Use llvm-gcc on 10.7/10.8

- Library/Formula/libpng.rb
Use llvm-gcc on 10.7 & 10.8 as building with clang results in a test failure.
Tested on 10.4 to 10.11 with respective default compilers (10.4 & 5 on powerpc)
Regarding revbumps, tested the `pilot-read-screenshot` from previously built pilot-link formula as a test without rebuild.
Worked fine (looking at the changes in readme.txt for previous two release, they just contain bug fixes).
> libpng 1.6.45

- Library/Formula/gmp.rb
Workaround is on longer required on 10.6 and slows down builds for all OS X versions.
Bump revision as assembly support is no longer explicitly disabled.
Add a test for static libraries from upstream
https://github.com/Homebrew/homebrew-core/blob/65f68fef5c44448232c8dab8b748baf33e8daf61/Formula/g/gmp.rb
Tested on OS X 10.6 as a 64bit build & 32bit build, with GCC 4.2 & llvm-gcc.
> gmp: Drop workaround for OS X 10.6

- Library/Formula/perl.rb
Tested on Tiger (G4/i386) with GCC 4.0.1 and Leopard (G5/i386) with GCC 4.2, 10.6 to 10.11.
Tiger/i386 fails several tests with regards to locale and Yosemite fails some tests regarding floating point, otherwise all other systems passed their testsuite run and should not block packaging for PowerPC. I'll follow up on 10.4/10.10 on intel separately.
> perl 5.40.1

- Library/Formula/openssl3.rb
`.previous` directive is unsupported by `as(1)`.
Skipping revbump to spare pointless rebuild on PowerPC/32bit x86 systems (it only applies to x86_64 builds)
Tested on 10.6 to 10.11, everything built successfully on all OS' but there's a new test failure in OpenSSL 3.4.0 on 10.6 & 10.7 which is unrelated to this build fix.
> openssl3: Fix build on 10.6 to 10.8

- Library/Formula/sqlite.rb
`___atomic_load_n()` / `___atomic_store_n()` called but not defined.
> sqlite: Use llvm-gcc on 10.7 & 10.8

- Library/Formula/gettext.rb
That way we can be specific about the affected clang version, rather than excluding by OS version.
> gettext: Use fails_with in block-form

- Library/Formula/palm-os-sdk.rb
- Library/Formula/pilot-link.rb
- Library/Formula/pilrc.rb
- Library/Formula/prc-tools.rb
Build tested on 10.4 (G4/G5/i386),10.5 (G5/i386), 10.6 to 10.11 (x86_64).
Actual use tested on 10.4 (G4) to build a [Hello World](https://en.wikibooks.org/wiki/Programming_for_Palm_OS%2FC%2FHelloWorld) app and run it on a Palm m515.
```
m68k−palmos−gcc hello.c −o hello
m68k−palmos−obj−res hello
build−prc hello.prc "Hello, World" WRLD *.hello.grc
pilot-xfer -p usb: -i hello.prc
```
> Add Palm OS development toolchain

- Library/Formula/dillo.rb
Enable webp support
Enable IPv6 support by default.
Remove the C++11 dependency so that GCC 4.0 can be used via https://github.com/dillo-browser/dillo/pull/353 _POSIX_C_SOURCE guards different sections on 10.4 to 10.5 & up. --disable-debug is unrecognised.
> dillo 3.2.0

- Library/Formula/libffi.rb
Make universal builds optional, fixes build on 10.6 & up where we build in 64-bit mode. Otherwise the build fails:
```
Undefined symbols for architecture i386:
"_ffi_prep_cif_machdep", referenced from:
_ffi_prep_cif_core in prep_cif.o
"_ffi_prep_closure_loc", referenced from:
_ffi_prep_closure in prep_cif.o
"_ffi_prep_raw_closure_loc", referenced from:
_ffi_prep_raw_closure in raw_api.o
ld: symbol(s) not found for architecture i386
```
It was originally introduced to help install the ffi gem using ruby 1.8.7 which shipped with Snow Leopard, in commit 2bcc4fccee3c8e8820448b65d2a3e243032e2ec5
Tested on Tiger PowerPC (G4) with GCC 4.0.1, Leopard (G4/i386) with GCC 4.2, Snow Leopard with GCC 4.2, Lion, Yosemite, El Capitan with clang
> libffi 3.4.7

- Library/Formula/gnupg.rb
In prep for installing GnuPG 2.x as gpg, install GnuPG 1.4.x binaries with a 1 suffix, so that there's no clashes.
Bit late now as GnuPG is ancient but no issue building with asm not disabled on Tiger.
Tested on Tiger (G5/i386) with GCC 4.0.1
> gnupg: Install as gpg1

- Library/Formula/libarchive.rb
Tested on Tiger (G4/i386) with GCC 4.0.1, Leopard (G5) with GCC 4.2, 10.7-10.10.
> libarchive 3.7.7

- Library/Formula/libassuan.rb
Tested with Tiger (G5/i386) with GCC 4.0.1, Lion to Yosemite with clang.
> libassuan 3.0.2

- Library/Formula/hercules.rb
Need a compiler with TLS support (GCC 4.0.1,4.2,llvm-gcc are out) Use up to date dependencies
Add a test from upstream
Testing on Tiger (G5/i386) with GCC 5 & 8, Lion & Yosemite with clang.
> hercules 3.13

- Library/Formula/python3.rb
Support for atomics is buggy and causes of backend failure in compiler.
In Apple LLVM 4.1 __atomic_load_n & __atomic_store_n were not implemented
so there was not an issue but with the command line tools from
Xcode 4.6.2 these functions are present & the build tries to make use
of them & fails.
fails:
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
lacks support:
Apple clang version 4.1 (tags/Apple/clang-421.11.66) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
Patch via Macports.
Tested on Lion with Command line tools from Xcode 4.6.2  (xcode462_cltools_10_76938260a.dmg)
Resolves #1294
> python3: Build fix for Apple LLVM 4.2 on 10.7

- Library/Formula/gettext.rb
- Library/Formula/libpng.rb
- Library/Formula/sqlite.rb
The issues with clang on Lion and Mountain Lion were due to my own mistake of having outdated command line tools installed.
With the latest version installed, there's no issue on Lion with clang-425.0.28 and Mountain Lion with clang-503.0.40.
> gettext/libpng/sqlite: revert clang exclusion

- Library/Formula/pcre.rb
Test fails on Leopard/i386 and El Capitan as well.
Resolves issue #1301
Tested on El Capitan with clang.
> pcre: just avoid JIT

- Library/Formula/cloog018.rb
- Library/Formula/libmpc.rb
- Library/Formula/libmpc08.rb
- Library/Formula/mpfr2.rb
Drop old package hashes which are no longer around.
> cloog018/libmpc/libmpc08/mpfr2: update urls

- Library/Formula/gcc47.rb
--enable-libstdcxx-time alters the C++11 ABI and shouldn't be used. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61758#c6
Allow the build itself to set the type of checking.
We're not building head so no need to specify disable werror.
Update URLs
Don't blindly enable LTO, it is not supported on PowerPC https://github.com/iains/darwin-toolchains-start-here/discussions/37#discussioncomment-3285847
Add a test for C++ & Fortran
Skip the conditional as the fix from the GCC bug was integrated into GCC.
Built on a 1.33Ghz PowerBook G4 running Tiger using GCC 4.0.1 in 333 minutes
Built on 1st gen 1.8Ghz iMac G5 running Tiger using GCC 4.0.1 in 295 minutes.
Built on Tiger/i386 with a 2Ghz c2d mac mini using GCC 4.0.1 in 63 minutes
Built on 1st gen 1.8Ghz iMac G5 running Leopard using GCC 4.2 in …
> gcc47: tweak build

- Library/Formula/cloog018.rb
v0.18.2 is the last version which is compatible with isl v0.11.x but install is broken.
Ensure that isl and gmp from Tigerbrew are used and not the bundled version of isl.
Tested across the board as part of testing changes gcc48 in pull request #1299
> cloog18 0.18.1

- Library/Formula/tree.rb
It now uses the common prefix capitalised
Need to state the root of the man directory, it will suffix the destination.
Add a license while here, obtained from
https://github.com/Homebrew/homebrew-core/blob/238f95575d520714c7b5f5914bd036693769ef41/Formula/t/tree.rb
> tree: add variables passed to make

- Library/Formula/gcc48.rb
- Library/Formula/mpfr2.rb
GCC 4.8 is the minimum version required to build GCC 14, ensure it builds ok
Builds fine with GCC 4.0 on Tiger.
Turn off optimisation to avoid compilation issues during a lengthy build.
--enable-libstdcxx-time alters the C++11 ABI and shouldn't be used. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61758#c6
Allow the build itself to set the type of checking.
We're not building head so no need to specify disable werror.
Update URLs
Use the default build config & address any fallouts, rather than use a debug bootstrap.
Tested on Tiger (G4/G5/i385) with GCC 4.0.1
Built on 600Mhz iBook G3 running Tiger  using GCC 4.0.1 in 1073 minutes.
Built on 1.33Ghz PowerBook G4 running Tiger using GCC 4.0.1 in 462 minutes.
Built on 1st gen 1.8Ghz iMac G5 running Tiger using GCC 4.0.1 in 401 minutes.
Built …
> gcc48: tweak build and update its dependencies

- Library/Formula/gmp4.rb
Needed for Tiger.
Always run the test suite for peace of mind.
Tested across the board with the gcc4.8 update in #1299
> gmp4: Allow building with GCC 4.0

- Library/Formula/openssl3.rb
Built with tests on a 1.8Ghz iMac G5 running Tiger in 181 minutes using GCC 4.0.1
Built with tests on a 2Ghz c2d mac mini running Tiger in 153 minutes using GCC 4.0.1
Built with tests on 1.33Ghz iBook G4 running Leopard using GCC 4.2 - forgot to note the time.
Built with tests on 1st gen 1.8Ghz iMac G5 running Leopard using GCC 4.0.1 in 114 minutes.
Built with tests on mid-2009 Air running Leopard using GCC 4.2 in 65 minutes.
Built with tests on late 2009 white MacBook running Mountain Lion using clang in 34 minutes.
Built with tests on late 2009 white MacBook running Mavericks using clang - forgot to note the time.
 Built with tests on late 2009 white MacBook running Yosemite using clang in 34 minutes.
Built with tests on mid-2009 Air running El Capitan using clang in 49 minutes.
Issues …
> openssl3 3.5.0

- Library/Formula/openssh.rb
Build tested on Tiger (i386) with GCC 4.0.1, Leopard (G4/G5/i386) with GCC 4.2, Snow leopard to El Capitan with their respective compilers.
> openssh 10.0p1

- Library/Formula/perl.rb
Tested with test suite on Tiger (G4/G5/i386) with GCC 4.0.1 and Leopard (G4/G5/i386) with GCC 4.2, Snow Leopard to El Capitan with their respective default compilers
[Tiger/i386 fails test suite run with 2 test failure related to locale](https://github.com/Perl/perl5/issues/23159)
Yosemite has 4 test failure like 5.40.1 which I need to investigate.
These 2 aside, all others passed their test suite run.
> perl 5.40.2

- Library/Formula/perl.rb
While here move the block further up in the file.
Cosmetic change, not build tested.
> perl: drop reference to a merged patch

- Library/Formula/maven.rb
Remove URL that's returning 404, promote mirror URL to main URL. Specify that Maven 3.3.3 requires Java 8, so that systems with lower versions fail the dependency check rather than fail with build errors.
Tested package download/dependency check on Leopard/PowerPC, but I don't have Java 8 on my development machine to test the build beyond this.
Resolves a maven build issue identified in https://github.com/mistydemeo/tigerbrew/issues/1332
> maven: fix download url and java dependency

- Library/Formula/fontconfig.rb
fontconfig fails to build without python3. This adds the python3 package as a dependency.
Tested on Leopard/PowerPC. This fixes an error discussed in https://github.com/mistydemeo/tigerbrew/issues/1332.
> fontconfig: add python3 dependency

- Library/Formula/geocouch.rb
Download is failing sha256 check. Updating to current checksum.
Confirmed this sha256sum is correct on two hosts. Build tested on Leopard/PowerPC. Resolves an issue discussed in https://github.com/mistydemeo/tigerbrew/issues/1332.
> geocouch: update sha256 checksum

- Library/Formula/lfe.rb
Download is failing sha256 check. Updating to current checksum.
Confirmed this sha256sum is correct on two hosts. Build tested on Leopard/PowerPC. Resolves an issue discussed in https://github.com/mistydemeo/tigerbrew/issues/1332.
> lfe: update sha256 checksum

- Library/Formula/rabbitmq.rb
Previous download url is returning 404, updating to github.com url.
Tested on Leopard/PPC. Resolves an issue identified in https://github.com/mistydemeo/tigerbrew/issues/1332
> rabbitmq: update download url

- Library/Formula/erlang.rb
SCTP support and OpenSSL support are enabled by default.
Cellar/erlang/18.1.5/lib/erlang/lib/crypto-3.6.1/priv/lib/crypto.so still links to libcrypto without these flags.
Can't depend on wxWidgets at the moment as 3.0 needs Leopard.
Bypass __int128_t detection on a G5 as it breaks the build, not an issue on Tiger/i386.
Tested on Tiger (G4/G5/i386) with GCC 4.0.1
> erlang: Support building on Tiger

- Library/Formula/rebar.rb
This is the last version of the project.
Development has now moved to rebar3. Needs a new version of OTP v19 or above
https://ferd.ca/you-ve-got-to-upgrade-rebar3.html
> rebar 2.6.4

- Library/Formula/cowsay.rb
URL for cowsay source has changed: updating both URL and checksum. Tested on Leopard/PowerPC:
```
kabooties-emac:~ kabootie$ brew install cowsay
==> Downloading https://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/cowsay_3.03+dfsg2.orig.tar.gz
##################################################################################################################################################################################################### 100.0%
==> /bin/sh install.sh /usr/local/Cellar/cowsay/3.03+dfsg2.orig
/usr/local/Cellar/cowsay/3.03+dfsg2.orig: 44 files, 192K, built in 10 seconds
kabooties-emac:~ kabootie$ brew fetch cowsay
==> Downloading https://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/c/cowsay/cowsay_3.03+dfsg2.orig.tar.gz
Already downloaded: …
```
> cowsay: fix url and checksum

- Library/Formula/elixir.rb
Update elixir to 1.5.3 and remove outdated bottle checksums. This is the latest version of `elixir` that is compatible with Erlang 18. Tested both with the current version of `erlang` as well as the version in PR https://github.com/mistydemeo/tigerbrew/pull/1344.
> elixir 1.5.3

- Library/Formula/wrangler.rb
Update wrangler to its latest release, 1.2. Tested with both the current version of `erlang` and https://github.com/mistydemeo/tigerbrew/pull/1344.
> wrangler 1.2

- Library/Formula/syntaxerl.rb
Update syntaxerl to version 0.13.0, later versions do not produce a `syntaxerl` program in /usr/local/bin/ which seems to be due to a `rebar3` dependency, which itself depends on OTP 19. No release notes are provided in Github for syntaxerl, so this may be resolvable under OTP 18, but will require more investigation. Tested against https://github.com/mistydemeo/tigerbrew/pull/1344.
> syntaxerl 0.13.0

- Library/Formula/ejabberd.rb
Updating ejabberd to 16.12. Version 16 is the first version I was able to build on Leopard/PPC, and 16.12 is the highest minor version of ejabberd 16.
Also switch to using openssl3.
Build successfully tested on Leopard/PPC, and sure enough I can connect Adium clients to the server. I would love help testing on Snow Leopard if anyone is able to, as the pam_appl.h workaround I needed to add is apparently not needed on SL, but I don't currently have a way to test that.
> ejabberd 16.12

- Library/Formula/erlang.rb
erlc built with GCC 4.2 fails with Bus error when it reaches HiPE build. Switch to llvm-gcc instead.
llvm-gcc may have had issues compiling OTP 14 & 16, but it work here for 18. Originally the exclusion was for 14 for llvm-gcc bulid 2334, then changed to an outright exclusion for OTP 16. Seems to be fine on 10.6 with llvm-gcc build 2335.6.
> erlang: Fix build on Snow Leopard

- Library/Formula/erlang.rb
We sidestepped dealing with this when the formula was upgraded to v18 by making use of the autoconf shipped with OS X which is fine up until 10.7 where autoconf was removed.
Tested on 10.7 to 10.11.
Remaining issue is on 10.11 erlang builds but will not link to the version of OpenSSL included with OS, need to fix crypto.c so OpenSSL 3 can be used.
> erlang: allow current autoconf to work

- Library/Formula/tcl-tk.rb
Build tested on Tiger (G5/i386) with GCC 4.0.1, Leopard (i386) with GCC 4.2 10.7 to 10.11 with clang.
There's one issue which prevents the build on Snow Leopard with the Aqua binding.
That'll be addressed separately.
> tcl-tk 8.6.16 + tcllib 2.0

- Library/Formula/ejabberd.rb
Small refactor, based on discussion in https://github.com/mistydemeo/tigerbrew/pull/1352#issuecomment-2832603798. Use a resource to manage downloading the erlang PAM dependency in a more canonical way. 
Built successfully on Leopard/PPC.
> ejabberd: add resource for pam dependency

- Library/Formula/ejabberd.rb
No reason why it needs to be isolated to specific OS version.
While here add a description for the lager version bump tweak.
Try to match code to the comment
> ejabberd: Use prefetched p1_pam for all builds

- Library/Formula/python.rb
The sphinx-doc option for python adds a dependency to a nonexistent package, 'sphinx-doc'. Remove.
Test build succeeded on Tiger/PowerPC, Leopard/PowerPC, Leopard/Intel, and Snow Leopard/Intel.
> python: remove sphinx-doc option

- Library/Formula/libidn2.rb
Update libidn2 from 2.3.7 to 2.3.8, latest available version. Remove now-out-of-date bottle hash. Also remove HEAD option, which adds a dependency on a nonexistent package called 'ronn'.
Test build succeeded on Tiger/PowerPC, Leopard/PowerPC, Leopard/Intel, and Snow Leopard/Intel.
> libidn2 2.3.8

- Library/Homebrew/os/mac.rb
This fixes finding GCC 14 in the compiler selection code; otherwise, the compiler selection machinery will pass it over for GCC 8.
Sample strings the regex is matching against:
gcc-8:
```
gcc-8 (Tigerbrew gcc8 8.5.0_1) 8.5.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
gcc-14:
```
gcc-14 (Tigerbrew gcc 14.2.0) 14.2.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
> non_apple_gcc_version: fix two-digit GCCs

- Library/Formula/erlang.rb
This contains a few build fixes for Erlang, which I've run into on Tiger with a G5 using GCC 14.
It still doesn't 100% build for me yet; I ran into a link error at the end: https://gist.github.com/mistydemeo/b26c6e21c356a88ad6eb5dd104ed00a4
```
/usr/local/bin/gcc-14 -o /private/tmp/erlang20250517-24809-1gecgbh/otp-OTP-18.3.4.11/bin/powerpc-apple-darwin8.11.0/beam.smp \
-m32 -L/usr/local/opt/zlib/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names  obj/powerpc-apple-darwin8.11.0/opt/smp/erl_main.o	obj/powerpc-apple-darwin8.11.0/opt/smp/preload.o obj/powerpc-apple-darwin8.11.0/opt/smp/beam_emu.o		obj/powerpc-apple-darwin8.11.0/opt/smp/beam_opcodes.o obj/powerpc-apple-darwin8.11.0/opt/smp/beam_load.o		obj/powerpc-apple-darwin8.11.0/opt/smp/beam_bif_load.o …
```
> Erlang build fixes

- Library/Formula/erlang.rb
Looks like this issue was fixed upstream in a later release. Fixes the issue I mentioned in #1368.
> erlang: fix build on GCC 14

- Library/Formula/boost.rb
- Library/Formula/faad2.rb
- Library/Formula/lame.rb
- Library/Formula/libvo-aacenc.rb
- Library/Formula/mad.rb
- Library/Formula/pianobar.rb
- Library/Formula/texi2html.rb
- Library/Formula/yasm.rb
Eight formulas have bottles that work, but which use sha1 checksums in the formula rather than sha256. This PR updates all these checksums to sha256.
Tested with `brew fetch` on `tiger_altivec` and `leopard_altivec`. I don't have a G3 mac for testing, so I wasn't able to confirm those checksums with `brew fetch`. 
```
Tiger-PowerPC:~ kabootie$ brew fetch boost faad2 libvo-aacenc pianobar texi2html
Fetching: boost, faad2, libvo-aacenc, pianobar, texi2html
==> Downloading https://ia904500.us.archive.org/24/items/tigerbrew/boost-1.58.0.tiger_altivec.bottle.tar.gz
Already downloaded: /Users/kabootie/Library/Caches/Homebrew/boost-1.58.0.tiger_altivec.bottle.tar.gz
SHA1: 8f6a8a1ee71302d218fde9b5837fdc32e52bc63d
SHA256: 9344005f51749e26ad13448df62c00a3d0bd92123b970fa673528884ff4e125c
==> …
```
> replace sha1 bottle checksums with sha256

- Library/Formula/frotz.rb
I'd like to submit a formula for [Frotz](https://davidgriffith.gitlab.io/frotz/), the interpreter for text adventure games.
Version 2.50 of Frotz and beyond need `_strndup`, which I think requires Mac OS X 10.7 Lion or later - but please correct me if you know a workaround for this. So version 2.44 looks to be the latest version that can be built on Mac OS X 10.4 through 10.6. 
Modern Frotz comes in three flavors - a curses-based variant, a 'dumb' variant, and an SDL/graphical variant. I'm not able to figure out the SDL variant right now, but I thought it'd be great to start with the other two while I figure out whether this version of SDL frotz is in fact buildable.
Tested on Tiger and Leopard PowerPC; and Tiger, Leopard, and Snow Leopard Intel.
> frotz 2.44

- Library/Formula/scheme48.rb
Source archive comes with documentation already generated from tex files. Use them instead of regenerating which would pull in a LaTeX dependency.
No need to adjust optimisation level when building with clang (tested on 10.7 to 10.11)
bibop garbage collector is the default.
Add an option to run the test suite.
This is the first formula where I've seen noticable difference in performance with the compiler optimisation.
With default optimisation settings it took 17 minutes to build & run the test suite.
With no_optimization set, it took 55 minutes to build & run the test suite. Tested on a 1.8Ghz iMac G5.
Tested on Tiger (G5), Leopard (i386) to El Capitan with the default compiler for each OS.
> scheme48 1.9.3

- Library/Contributions/brew_bash_completion.sh
- Library/Formula/bash-completion.rb
The bash autocomplete script at `Library/Contributions/brew_bash_completion.sh` gives an error when running on the default bash version (2.05b.0(1)-release) on Mac OS X 104 / Tiger: `-bash: complete: bashdefault: invalid option name`. 
Completions work on Tiger if I remove the `bashdefault` option from the `complete` command.  The script works as-is with the default bash version in Leopard (3.2.17(1)-release) and Snow Leopard (3.2.48(1)-release). 
I'm adding a test for which version of bash is in use, and using the appropriate command for bash <= 2 and bash => 3.
> don't use bashdefault option on bash version <= 2

- Library/Formula/lesstif.rb
Fails to resolve
_FcPatternCreate
_FcPatternDestroy
_FcPatternAddInteger
_FcPatternAddString
The fontconfig supplied with the system's X11 has support but opted to use a recent version from Tigerbrew instead.
Fixes #1386
> lesstif: help linking against fontconfig

- Library/Formula/libaacs.rb
v0.9.0 is the most recent version which compiles out of the box on Leopard. It's possble to get this to compile on Tiger but I decided on not including the patch since the most recent version of VLC which runs on Tiger is v0.9.10.
I also lack the hardware and any other software which could use libaacs in order to be able to test beyond compilation.
Let me know if you want to give it a try.
Build tested on Leopard PowerPC (G4) with GCC 4.2
> libaacs 0.9.0

- Library/Formula/tmux.rb
Fixes build on 10.5 and up.
Tested on 10.4 (G5/i386), 10.5 (G4), 10.6 to 10.11.
Just as a heads up: Terminal.app on OS versions prior to 10.11 print `1;2c` when tmux is first invoked (fresh install, default config).  I don't have a solution/workaround for that yet.
> tmux: use relevant macro for os version guards

- Library/Formula/libnghttp2.rb
Tested on Tiger PowerPC (G5) with GCC 4.0.1.
Curl is still happy utilising http/2 functionality without a rebuild so have not bumped revision.
> libnghttp2 1.66.0

- Library/Formula/mtr.rb
You can get away with using Terminal.app, update caveats section.
> mtr: Braille output requires UTF-8

- Library/Formula/apr-util.rb
It doesn't enable it by default.
Best to just rely on expat for everything.
Tested to Tiger PowerPC (G5) with GCC 4.0.1
> apr-util: Need to explicitly enable crypto support

- Library/Formula/libiscsi.rb
Install example programs which are normally marked for noinst. Only depend on cunit if built with test-tool option. popt is no longer required.
Build tested only, on OS X Tiger. Don't have an iSCSI target at hand.
Resolves #692
> libiscsi 1.20.2

- Library/Formula/arp-scan.rb
Requires libpcap with `pcap_set_immediate_mode()` support, introduced in libpcap 1.5.
Fixes issue #1396
> arp-scan 1.10.0

- Library/Formula/git.rb
To build Git-Gui.app Tcl-Tk 8.5 with Aqua support is required.
Snow Leopard shipped with Tcl-Tk 8.5.
Unable to use an up to date version of Tcl-Tk via Tigerbrew since Tk requires functionality in AppKit introduced in Snow Leopard for Aqua support.
Perhaps an option is to not build the .app and see if it can be run via X11 support on Leopard and prior.
Fixes issue #1410
> git: Fix build on Leopard

- install
This mirror allows HTTP-only connections and should be more stable for installations than archive.org. Once we have this, we can then use it to fetch other packages from HTTPS-requiring sources.
This should fix remaining issues like the ones discussed in #918.
This mirror was graciously provided by @XerTheSquirrel.
cc @sevan
> bootstrap curl: use HTTP-only mirror

- Library/Homebrew/cmd/vendor-install.sh
Install from the same HTTP-only mirror as the installer - see #1417.
> vendor-install: use http-only mirror

- Library/Formula/python3.rb
Built on 1st gen 1.8Ghz iMac G5 running Tiger using GCC 4.0.1
Built on mid-2009 Air running Snow Leopard using GCC 4.2 in 6.1 minutes
Built on late 2009 white MacBook running Yosemite using clang in 4.2 minutes
Built on mid-2009 Air running El Capitan using clang in 7.3 minutes
Marking as draft until I've done more testing.
> python 3.10.18

- Library/Formula/links.rb
Rework options, hang image support off X11 support, and make X11 support default.
Pull in up to date deps, with the exception of fontconfig and by indirect dependency freetype as it causes issues starting in graphics mode on 10.6, and has a build issue on 10.7 which need to be resolved before they can be depended on.
Tested on Tiger PowerPC (G4/G5) with GCC 4.0.1, Snow Leopard with GCC 4.2, Lion with Clang.
> links 2.30

- Library/Formula/openssh.rb
Need to patch for lack of clock_gettime(3) on 10.11 and prior.
Tested on 10.4 to 10.11.
Tested on 10.4 (G4/G5) with GCC 4.0.1, 10.5 (i386) wth GCC 4.0.1 & 4.2
Missed 10.4 i386 and 10.5 PowerPC
> openssh 10.1p1
