- Library/Formula/mysql.rb
fixes #404
tested on my 10.5.8 G4
> mysql: update to version 5.6.35

- Library/Formula/cairo.rb
- Library/Formula/glib.rb
Also updates to the latest version.
Fixes #452.
cc @ranma42 - mind testing this?
> cairo: fix build on 10.4

- Library/Formula/ruby.rb
The inreplace is obviously an ugly, ugly hack; I'm just fitting this in for now until I report this upstream and there's a real patch.
Fixes #473.
> ruby: fix build on Tiger

- Library/Formula/icu4c.rb
refs #467
cc @ranma42 - I added a link to your PR here.
> icu4c: update patch syntax

- Library/Homebrew/hardware.rb
- Library/Homebrew/os/mac/hardware.rb
Adapted from Homebrew/brew#2496.
> Hardware::CPU.can_run? arch helper

- Library/Formula/qemu.rb
> qemu: fix build on 10.5

- Library/Formula/cloog-ppl015.rb
- Library/Formula/cloog018.rb
- Library/Formula/gmp4.rb
- Library/Formula/isl011.rb
- Library/Formula/isl014.rb
- Library/Formula/libmpc08.rb
- Library/Formula/mpfr2.rb
- Library/Formula/ppl011.rb
These were missed in the last PR.
Fixes #502.
> Import GCC formulae dependencies

- Library/Homebrew/dev-cmd/linkage.rb
- Library/Homebrew/os/mac/linkage_checker.rb
Adapted from various Homebrew commits - not importing those commits as Tigerbrew's source has drifted too far. This is just here to bootstrap my way through building portable packages!
> Import linkage checker

- Library/Formula/alpine.rb
Update URL to Alpine information and source code
> alpine: Update URL for information and source code

- Library/Formula/timedog.rb
> timedog 1.4

- Library/Formula/unar.rb
Fixes #542.
Unfortunately I can't get the newer version to build (or this version!), so I'll tackle that in a later PR.
> unar: update tarball url

- Library/Formula/doxygen.rb
> doxygen: strip incompatible flag on Tiger

- Library/Homebrew/utils.rb
> curl: pass --insecure on 10.6

- Library/Formula/gcc.rb
- Library/Formula/gmp.rb
- Library/Formula/isl.rb
- Library/Formula/mpfr.rb
- Library/Homebrew/compilers.rb
cc @mmolinac - I'm currently testing this as a potential fix. If this doesn't work, I'm going to attempt passing the `-force_cpusubtype_ALL` flag; this fixed a similar issue in #32.
> Upgrade GCC to 7.2.0

- Library/Formula/gcc44.rb
- Library/Formula/gcc45.rb
- Library/Formula/gcc46.rb
- Library/Formula/gcc47.rb
- Library/Formula/gcc48.rb
- Library/Formula/gcc49.rb
- Library/Formula/gcc5.rb
- Library/Formula/gcc6.rb
> Backport G3 GCC fix to older GCCs

- Library/Formula/curl-ca-bundle.rb
> curl-ca-bundle: add archive.org mirror

- install
cc @cjbayliss - this should fix the error you encountered.
> Refuse to try git installs on old OS Xs due to TLS

- Library/Formula/qemu.rb
Fixes #523.
cc @LarBob - I'm still testing this, but it probably doesn't work yet.
> Revert to QEMU 2.2.1

- Library/Formula/gcc44.rb
Builds on G4/Intel Tiger/Leopard.
> gcc44: fix build for all

- Library/Formula/libpcap.rb
> libpcap: needs newer bison/flex

- Library/Formula/fish.rb
> fish: fix Tiger build

- Library/Formula/readline.rb
Fixes #585.
This replaces the existing Tiger Altivec bottle (which never got uploaded) and adds a new G3 bottle.
> readline: add Tiger bottles

- Library/Formula/mgba.rb
> mgba 0.6.3

- Library/Formula/qt.rb
> qt: fix download URL

- Library/ENV/4.3/cc
> superenv: filter out -Wno-implicit-fallthrough

- Library/Formula/coreutils.rb
> Coreutils 8.30

- Library/Formula/libid3tag.rb
> libid3tag: fix patches

- Library/Formula/mariadb.rb
> mariadb: fix URLs

- Library/Formula/popt.rb
I updated the URL in the formula for popt as old the url didn't seem to be working anymore.
Best regards
pk2061
> Updated URL for popt.rb

- Library/Formula/libconfig.rb
I updated the download link to version 1.7.2 as version 1.5 was no longer available on the server.
> Update libconfig.rb to install version 1.7.2

- Library/Formula/exiv2.rb
> exiv2: fix URL

- Library/Homebrew/formula.rb
This should fix #712 and #711. Not yet tested.
> Formula: backport license support

- Library/Homebrew/cmd/vendor-curl.sh
- Library/brew.sh
Fixes #710, and probably other issues too.
> Use newer curl and ruby

- Library/Formula/dirmngr.rb
Closes #780.
Signed-off-by: Alyssa Ross <hi@alyssa.is>
Signed-off-by: Benson Leung <bleung@chromium.org>
> dirmngr: fix patch URL

- Library/Formula/the_silver_searcher.rb
The current formula attempts to build version 0.31.0, but fails on Tiger.
This PR updates the_silver_searcher to 0.33.0 and fixes the build on Tiger.
Updating past 0.33.0 would require more substantial patches.
> the_silver_searcher: Update to 0.33.0 and fix build on Tiger

- Library/Formula/bsdmake.rb
- Library/Formula/cctools-headers.rb
- Library/Formula/cctools.rb
- Library/Formula/cvs.rb
- Library/Formula/dyld-headers.rb
- Library/Formula/ld64.rb
- Library/Formula/libunwind-headers.rb
- Library/Formula/libutil.rb
- Library/Formula/md.rb
> Replace Apple tarball links with GitHub tarball links

- Library/Formula/tmux.rb
This PR updates tmux from version 2.0 to 3.2a.
I selected 3.2a because I couldn't get mouse support to work in the latest version (3.3a).
> tmux: update to 3.2a

- Library/Formula/bitchx.rb
Update autoconfig bits to support OpenSSL 1.1.x and newer, as well as support building on Tiger with legacy toolchain.
Needs https://github.com/mistydemeo/tigerbrew/pull/805
> bitchx: Build fix for Tiger and current OpenSSL

- Library/Formula/cyrus-sasl.rb
Looks like the old FTP isn't responding.
> cyrus-sasl: fix url

- Library/Formula/bitchx.rb
- Library/Formula/curl.rb
- Library/Formula/cyrus-sasl.rb
- Library/Formula/dovecot.rb
- Library/Formula/git.rb
- Library/Formula/ldns.rb
- Library/Formula/libevent.rb
- Library/Formula/libxml2.rb
- Library/Formula/libxslt.rb
- Library/Formula/lynx.rb
- Library/Formula/mutt.rb
- Library/Formula/openssh.rb
- Library/Formula/openssl.rb
- Library/Formula/postgresql.rb
- Library/Formula/python.rb
- Library/Formula/python3.rb
- Library/Formula/tmux.rb
- Library/Formula/tokyo-cabinet.rb
This branch contains both an OpenSSL bump and a variety of packages that need to be upgraded alongside it to avoid getting broken.
> OpenSSL 1.1

- Library/Formula/curl.rb
Drop libidn support since curl requires libidn2 which is currently not packages and the option is no longer recognised by configure script. Rework so we only ever use openssl from tigerbrew, it's unlikely we'll ever want to use the version supplied by OS on legacy release now.
> curl 8.2.1

- Library/Formula/curl.rb
This incorporates extra build steps from the upstream Homebrew formula.
> curl: add extra install steps

- Library/Formula/bzip2.rb
It has received many CVEs over the years.
> bzip2: Add a formula for v1.0.8

- Library/Formula/poke.rb
Formula adapted from
https://raw.githubusercontent.com/Homebrew/homebrew-core/f357e4c65c5a923db687100ac4167232299b3983/Formula/poke.rb
Tested on Tiger with GCC 4.0.1
> poke: Add formula for v3.2

- Library/Formula/git.rb
v2.40.1 formula was missing support for Leopard in `config.mak.uname` patch.
Tested on Tiger with GCC 4.0.1 & Leopard with GCC 4.2.
`git-credential-osxkeychain` is only build tested, I don't have a working setup.
> git 2.41.0

- Library/Formula/qemu.rb
Tested on i386 with GCC 5
Fixes #931
> QEMU Leopard build fix

- Library/Formula/xxhash.rb
Adapted from
https://github.com/Homebrew/homebrew-core/blob/a78cbe4ff3223795b80705287c53eebe602b7c85/Formula/xxhash.rb
> xxhash: Add formula for v0.8.1

- Library/Formula/sqlite.rb
Tested on
Leopard i386 & ppc, GCC 4.2
Tiger ppc, GCC 4.0.1
> sqlite 3.42.0

- Library/Formula/ntp.rb
Adapted from
https://raw.githubusercontent.com/Homebrew/homebrew-core/a5a3274dc89f48d7853241955660e00b479e473e/Formula/n/ntp.rb
Tested on
Tiger ppc, GCC 4.0.1
Leopard i386, GCC 4.2
Indirectly resolves #671
> ntp 4.2.8p17

- Library/Formula/openvpn.rb
Requires #817, #939
Tested on Tiger ppc, GCC 4.0.1
> openvpn 2.6.6

- Library/Formula/irssi.rb
OpenSSL support is required now.
Use up to date dependencies rather than what provided by OS for security.
There is currently a bug with building botti when Perl support is also enabled, so disable it for now.
https://github.com/irssi/irssi/issues/1374
Should go to the OpenSSL branch, needs #805, or should be merged after, with #878
Only tested on Tiger, needs testing on newer OS'.
> irssi: Upgrade formula to v1.4.4

- Library/Formula/bison.rb
Trim dependencies on Tiger since we don't touch build infra, new autotools are not needed.
> bison: Upgrade formula to v3.8

- Library/Formula/bash.rb
Drop dead mirrors.
Should be merged after #829
> bash: Upgrade formula to v5.2.15

- Library/Formula/expat.rb
--disable-debug is unrecognised.
> expat: Upgrade formula to v2.5.0

- Library/Formula/git.rb
> git 2.42.0

- Library/Formula/tenfourfox.rb
While here, switch to using SHA2-256 hashes
> tenfourfox: Upgrade formula to vFPR32.5

- Library/Formula/sqlite.rb
> sqlite 3.43.0

- Library/Formula/apr.rb
Seems to build ok now without deparallelize.
> apr: Upgrade formula to v1.7.4

- Library/Formula/apr-util.rb
Ideally should be merged after PR #814 to upgrade apr
> apr-util: Upgrade formula to v1.6.3

- Library/Formula/trurl.rb
Adapted from https://github.com/Homebrew/homebrew-core/blob/c3fd4150a2feaed109193d06478dbc71fe6143ae/Formula/trurl.rb
> trurl: Add formula for v0.8

- Library/Formula/mercurial.rb
Required when PR https://github.com/mistydemeo/tigerbrew/pull/805 is merged
> mercurial: Upgrade formula to v6.5.1

- Library/Formula/rsync.rb
Adapted from
https://github.com/Homebrew/homebrew-core/blob/a76c6520515986d4c77bab61cab99076bcc2b727/Formula/rsync.rb
Resolves #791 
Need PR #825 to build, and ideally #824
> rsync: Add formula for v3.2.7

- Library/Formula/midnight-commander.rb
unrecognized options: --disable-debug
Requires #809 #850 #844 #805 
Resolves #500 #375
> midnight-commander: Upgrade formula to v4.8.29

- Library/Formula/isl.rb
- Library/Formula/isl011.rb
- Library/Formula/isl014.rb
> Update urls for ISL formulas

- Library/Formula/python.rb
With setuptools-44.1.1, pip-20.3.4, wheel-0.37.1
> python: Upgrade formula to v2.7.18

- Library/Formula/gcc.rb
- Library/Formula/gcc5.rb
- Library/Formula/gcc6.rb
- Library/Formula/gmp.rb
- Library/Formula/libmpc.rb
- Library/Formula/mpfr.rb
This will contain the GCC 5.5 upgrade and the dependencies for the GCCs.
> GCC upgrade staging branch

- Library/Formula/curl.rb
Dropped the mirror since [the cURL website is no longer mirrored](https://curl.se/mirror/)
> curl 8.3.0

- Library/Formula/openssh.rb
Tested on 10.4 (G4) & 10.5 (G5)
Should we think about switch over to OpenSSL 3?
> openssh 9.5p1

- Library/Formula/openssl3.rb
Tested on Tiger powerpc, took just over 2 hours.
> openssl3 3.1.4

- Library/Formula/av98.rb
That gives us a Gemini client via Python 3.
Ideally needs https://github.com/mistydemeo/tigerbrew/pull/805,  #823
> av98: Add a formula for AV-98 v1.0.1

- Library/Formula/czmq.rb
- Library/Formula/libgpg-error.rb
- Library/Formula/libpgm.rb
- Library/Formula/norm.rb
- Library/Formula/zeromq.rb
> Fix various source tarballs

- Library/Formula/git.rb
> git 2.42.1

- Library/Formula/lighttpd.rb
> lighttpd 1.4.73

- Library/Formula/gengetopt.rb
> gengetopt 2.23

- Library/Formula/gnu-units.rb
> gnu-units 2.22

- Library/Formula/flvstreamer.rb
Drop the hashes of old intel bottles.
> flvstreamer: fix url

- Library/Formula/freetype.rb
Add dependencies, test target works now.
> freetype 2.13.2

- Library/Formula/findutils.rb
> findutils 4.9.0

- Library/Formula/bison.rb
> bison 3.8.2

- Library/Formula/autoconf.rb
> autoconf 2.71

- Library/Formula/autoconf-archive.rb
> autoconf-archive 2023.02.20

- Library/Formula/automake.rb
> automake 1.16.5

- Library/Formula/vala.rb
Built on Tiger (G5) with GCC 4.0.1
Should be merged after #989
> vala 0.56.14

- Library/Formula/bash.rb
> bash 5.2.21

- Library/Formula/mtools.rb
Build tested (with & without X11 support) only as I don't have a floppy hooked up.
Tested on Tiger powerpc
> mtools 4.0.43

- Library/Formula/openssh.rb
Tested on Tiger (G5) with GCC 4.0.1 .
> openssh 9.6p1

- Library/Formula/sqlite.rb
Tested on Tiger (G4 & 5) with GCC 4.0.1 .
> sqlite 3.44.2

- Library/Formula/fftw.rb
> fftw 3.3.10

- Library/Formula/zlib.rb
Tested on a G5 with Tiger & GCC 4.0.1
> zlib 1.3.1

- Library/Formula/xxhash.rb
> xxhash 0.8.2

- Library/Formula/perl.rb
> perl 5.38.2

- Library/Formula/exiftool.rb
Tested on Tiger using `/usr/bin/perl` (v5.8.6)
> exiftool 12.74

- Library/Formula/makedepend.rb
> makedepend 1.0.8

- Library/Formula/libgpg-error.rb
> libgpg-error 1.20

- Library/Formula/libgcrypt.rb
> libgcrypt 1.10.3

- Library/Formula/python3.rb
While here, switch to using openssl3.
Tested on Tiger powerpc
Ideally should be merged after the openssl3 update in #981
> python3: 3.7.17

- Library/Formula/nettle.rb
> nettle: use openssl3

- Library/Formula/ipcalc.rb
Tested on Tiger powerpc (G5) with Perl 5.8.6 included with OS
> ipcalc 0.51

- Library/Formula/gnu-indent.rb
> gnu-indent 2.2.13

- Library/Formula/libusb-compat.rb
> libusb-compat 0.1.8

- Library/Formula/stow.rb
Tested on Tiger powerpc (G5) with Perl from Tigerbrew (doesn't work out of the box with version included with OS).
> stow 2.4.0

- Library/Formula/rsync.rb
> rsync 3.3.0

- Library/Formula/nasm.rb
> nasm 2.16.02

- Library/Formula/chibi-scheme.rb
Tested on Tiger powerpc (G4 & G5) with GCC 4.0.1
> chibi-scheme 0.10.0

- Library/Formula/autossh.rb
> autossh 1.4g

- Library/Formula/cscope.rb
> cscope 15.9

- Library/Formula/osxutils.rb
Sync with
https://github.com/Homebrew/homebrew-core/blob/be982d27247e210cc3d76dc99ef332fe38e6ef7e/Formula/o/osxutils.rb
> osxutils 1.9.0

- Library/Formula/curl.rb
> curl 8.7.1

- Library/Formula/fltk.rb
> fltk 1.3.9

- Library/Formula/dillo.rb
> dillo: Add formula for v3.1.0

- Library/Formula/expat.rb
Turn off the optional tests as they require a C++11 compiler.
Resolves #1122
> expat 2.6.2

- Library/Formula/pngcheck.rb
> pngcheck 3.0.3

- Library/Formula/pcre2.rb
> Fix pcre2 non-existing patchfile

- CONTRIBUTING.md
File was renamed a while back.
> CONTRIBUTING.md: fix Code of Conduct link

- Library/Formula/xz.rb
> xz: Add a temporary mirror for source

- Library/Formula/ipinfo.rb
> ipinfo 1.2

- Library/Formula/newlisp.rb
> newlisp 10.7.5

- Library/Formula/libogg.rb
> libogg 1.3.5

- Library/Formula/json-c.rb
> json-c 0.17

- Library/Formula/perl.rb
Tested on Tiger powerpc (G5) with GCC 4.0.1., Leopard powerpc (G4) with GCC 4.2
Took 108.3 minutes on a 1.8Ghz iMac G5. 132mins on a 1.33Ghz iBook G4.
> perl 5.40.0

- Library/Formula/curl.rb
> curl 8.8.0

- Library/Formula/ragel.rb
> ragel 6.10

- Library/Formula/libxml2.rb
Tested on Tiger powerpc (G5) with GCC 5.5
> libxml2 2.11.8

- Library/Formula/libidn2.rb
> libidn2 2.3.7

- Library/Formula/a52dec.rb
Thanks to @Randrianasulu for the heads up.
> a52dec: url fix

- Library/Formula/libunistring.rb
> libunistring 1.2

- Library/Formula/libgpg-error.rb
> libgpg-error 1.51

- Library/Formula/libgpg-error.rb
Homebrew does this, and it's necessary for libassuan to install its own -config script.
> libgpg-error: install -config script

- Library/Formula/libassuan.rb
> libassuan 3.0.1

- Library/Formula/libgcrypt.rb
> libgcrypt 1.11.0

- Library/Formula/libunistring.rb
> libunistring 1.3

- Library/Formula/jsoncpp.rb
> jsoncpp 0.10.7

- Library/Formula/gpatch.rb
Based on
https://raw.githubusercontent.com/Homebrew/homebrew-core/5c4c48d20e350adc9b7dd9fde84092736235f1c7/Formula/g/gpatch.rb
Tested on Tiger (c2d/G5) with GCC 4.0 & 4.2
> gpatch: Add formula for patch 2.7.6

- Library/Formula/readline.rb
Add patches to readline 8.2 and fix test.
> readline 8.2.13

- Library/Formula/c-ares.rb
Tested on Tiger powerpc (G5) with GCC 4.0.1 + curl --with-c-ares
> c-ares 1.27.0

- Library/Formula/libpng.rb
> libpng 1.6.43

- Library/Formula/mercurial.rb
Tested on Tiger with Python 3.10.14
> mercurial 6.6.3

- Library/Formula/unixodbc.rb
> unixodbc 2.3.12

- Library/Formula/freetds.rb
> freetds 1.4.24

- Library/Formula/vim.rb
> vim 9.1.0990

- Library/Formula/dfu-util.rb
Should be merged after https://github.com/mistydemeo/tigerbrew/pull/1066
> dfu-util 0.11

- Library/Formula/dfu-programmer.rb
Should be merged after https://github.com/mistydemeo/tigerbrew/pull/1066
> dfu-programmer 1.1.0

- Library/Formula/open-ocd.rb
Tested with an ST-link v2 & STM32F103 on Tiger (G5) with GCC 4.0.1, Leopard (intel) with GCC 4.2, El Capitan with clang.
> openocd 0.12.0

- Library/Formula/radare2.rb
Radare currently splits its Darwin support between architectures so the changes proposed here are for powerpc support.
Based on
https://github.com/Homebrew/homebrew-core/blob/dcbbedf1c0590996b3b76ebc7b9eff92ebc5db73/Formula/r/radare2.rb
Tested on Tiger powerpc (G5) with GCC 5
Should be merged after #1072
> radare2 5.9.0

- Library/Formula/libdnet.rb
Python/cython is a build requirement now
Requires #1228 #1135
> libdnet 1.18.0

- Library/Formula/curl.rb
> curl 8.11.1

- Library/Formula/expat.rb
Tested on Tiger PowerPC (G4/G5)
> expat: fix test

- Library/Formula/python3.rb
With the upgrade to 3.10.16, builds on a Tiger G4 resulted in the ctype module not building. It turns out that it libffi was being linked against opportunistically via pkg-config in some scenarios. Just depends on libffi since the version found in the source of Python (Modules/_ctypes/libffi_osx) is very old (a pre-release of 2.0).
Some modules also link against zlib so depend on that too. Add a test to ensure the ctype module works in that it imports as the build of module can fail and the build of Python can succeed only to find that there no module to import later.
While here add a guard for tkinter test since only on Xorg X11 in 10.5 and up will X11 be started and the test run within. On Tiger you have in invoke the test from xterm otherwise it'll just fail.
Tested on Tiger …
> python3: Switch to using libffi formula

- Library/Formula/git.rb
> git 2.48.1

- Library/Formula/perl.rb
Sorry, forgot to do it with the update to 5.40.1.
> perl: drop hash of old bottle

- Library/Formula/vim.rb
Fixes #1265
Tested on Tiger PowerPC (G5) with GCC 4.0.1.
> vim 9.1.1076

- Library/Formula/webp.rb
Tested on Tiger PowerPC with GCC 4.0.1
> webp 1.5.0

- Library/Formula/dillo.rb
Found with `brew linkage dillo`
> dillo: add missing dep

- Library/Formula/fltk.rb
Built on Tiger PowerPC (G4) with GCC 4.0.1.
> fltk 1.3.11

- Library/Formula/curl.rb
> curl 8.12.0

- Library/Formula/git.rb
git-credential-osxkeychain missing header.
While here, move patch section up.
Tested on Lion with clang.
> git: fix build on 10.7

- Library/Formula/ninja-ide.rb
Save anyone wasting time on Tiger.
> ninja-ide: add Leopard dependency

- Library/Formula/curl.rb
Tested on Tiger (G4/i386) with GCC 4.0.1, Leopard (G5) with GCC 4.2, 10.7-10.10.
> curl 8.12.1

- Library/Formula/libusb.rb
Build tested on Lion & Mountain Lion.
> libusb: build fix for Lion

- Library/Formula/openssh.rb
Tested on Tiger (G5/i386) with GCC 4.0.1
> openssh 9.9p2

- Library/Formula/isl014.rb
The bottles are no longer around.
> isl014: drop old bottle hashes

- Library/Formula/git.rb
Built on Tiger/PowerPC (G5) with GCC 4.0.1
> git 2.49.0

- Library/Formula/libmpc08.rb
Tested across the board as part of testing changes gcc48 in pull request https://github.com/mistydemeo/tigerbrew/pull/1299
> libmpc08 0.8.2

- Library/Formula/curl.rb
Tested on Tiger/PowerPC (G5) with GCC 4.0.1
> curl 8.13.0

- Library/Formula/curl-ca-bundle.rb
> curl-ca-bundle 2025-02-25

- Library/Formula/libarchive.rb
Tested on Tiger/PowerPC (G5) with GCC 4.0.1
> libarchive 3.7.9

- Library/Formula/xz.rb
It's fairly short with 19 tests
> xz: run the test suite

- Library/Formula/isl011.rb
Always run the test suite for peace of mind.
Tested across the board with the gcc4.8 update in #1299
> isl011 0.11.2

- README.md
> Document how to run `brew update`

- Library/Formula/yaws.rb
One last extremely small PR tonight, just to correct the homepage for the yaws web server, which I discovered had moved while I was testing builds of erlang-based packages.
> yaws correct homepage

- Library/Formula/dos2unix.rb
Both versions tested on Tiger powerpc (G5) with GCC 4.0.1
> dos2unix 7.5.2 / 7.5.3-beta7

- Library/Formula/jansson.rb
> jansson 2.14.1

- Library/Formula/tcl-tk.rb
GCC 4.2 on 10.6 doesn't like the turnary operation there, but if you split it out, it works. Fixes #1361
Add missing brace to allow the test suite to run on 10.7 & prior.
Can't use the usual patch method which Tigerbrew provides to patch a resource, so have to invoke patch(1) via system method.
Tested on Snow Leopard (x86_64) with GCC 4.2.
> tcl-tk: Tk build fixes

- Library/Formula/sqlite.rb
Try to match the default options as upstream formula. https://github.com/Homebrew/homebrew-core/blob/b2e9f249f08f524995dfbc892474bd1b6e27e246/Formula/s/sqlite.rb
Adjust default sync setting based on advice from https://avi.im/blag/2025/sqlite-fsync/
--enable-dynamic-extensions is default now and not a recognised option.
Use modern zlib from tigerbrew.
Left icu option but it is untested.
SQLITE_ENABLE_JSON1 is default now, no need to enable it explicitly.
> sqlite 3.50.4

- Library/Formula/sqlite-analyzer.rb
Need to use a version of TCL newer than provided by Tiger.
> sqlite-analyzer 3.50.4

- Library/Formula/libuv.rb
Tested on Leopard PowerPC (G4) with GCC 4.2
> libuv: test build fix

- Library/Formula/cmake.rb
Tested on Leopard PowerPC (G4) with GCC 4.2
> cmake: Need libuv on Leopard

- Library/Formula/gmp4.rb
- Library/Formula/gnupg.rb
- Library/Formula/gnupg2.rb
- Library/Formula/isl011.rb
- Library/Formula/libmpc08.rb
- Library/Formula/libpng.rb
- Library/Formula/mpfr2.rb
- Library/Formula/openssl.rb
This should help users get up and running quicker.
> Only run test suite if requested on more packages
